src/storage/mongodb/MongoDBStorage.ts
=> Add missing }

README.md, src/client/ocpi/CpoOCPIClient.ts
=> README.md: Refine unit tests configuration documentation.

src/scheduler/SchedulerManager.ts, src/storage/mongodb/OCPPStorage.ts, src/types/ChargingStation.ts
And a run of `npm run import-sort`
=> Update ev-aws submodule

src/client/ocpi/CpoOCPIClient.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/CPOLocationsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIMapping.ts
Content:
- [CPO] Fix possible missing last_updated in location response
- [CPO] Increase tokens page size
=> [OCPI][CPO] Fix possible issues

src/server/rest/CentralRestServer.ts
And avoid ping timeout disconnection.
=> SocketIO: Track client disconnection reason

src/server/rest/CentralRestServer.ts
=> Increase socketIO ping interval.

src/server/rest/CentralRestServer.ts, src/storage/mongodb/MongoDBStorageNotification.ts, src/types/Authorization.ts
=> Add changes in charging profiles and cars collections to socket.io.

src/server/ocpp/json/WSConnection.ts, src/server/rest/service/UserService.ts
=> OCPP WS: Give more informations on JSON parsing error.

package-lock.json, package.json
=> Apply security updates to dependencies.

package-lock.json, package.json, src/server/ExpressTools.ts, src/server/ocpp/json/JsonCentralSystemServer.ts, src/server/ocpp/json/JsonRestWSConnection.ts, src/server/ocpp/json/JsonWSConnection.ts, src/server/ocpp/json/WSConnection.ts, src/server/ocpp/json/WSServer.ts, src/server/ocpp/services/OCPPService.ts, src/server/ocpp/soap/SoapCentralSystemServer.ts, src/server/ocpp/soap/services/SoapCentralSystemService12.ts, src/server/ocpp/soap/services/SoapCentralSystemService15.ts, src/server/ocpp/soap/services/SoapCentralSystemService16.ts, src/storage/mongodb/ChargingStationStorage.ts, src/types/ChargingStation.ts, src/types/configuration/CentralSystemServer.ts, src/types/configuration/WSClientConfiguration.ts, src/types/ocpp/OCPPHeader.ts, test/api/OCPPAllVersionsTest.ts, test/api/OCPPCommonTests.ts, test/api/ocpp/soap/OCPPSoapService15.ts
=> Keep track of the local OCPP server IP used by a charging station.

src/storage/mongodb/MongoDBStorageNotification.ts
I need deploy that change on the production landscape only for a few minutes to check if MongoDB changes notifications are working properly or not. 
Better if we do it in sync.   
=> Add log to check if DB changes are correctly done by MongoDB.

build/webpack.common.js
=> Fix Convergent Charging missed files during build.

src/server/rest/service/AuthService.ts, src/server/rest/service/ChargingStationService.ts, src/server/rest/service/security/AuthSecurity.ts, src/server/rest/service/security/BillingSecurity.ts, src/server/rest/service/security/RegistrationTokenSecurity.ts, src/types/requests/HttpTransactionRequest.ts, src/types/requests/HttpUserRequest.ts, src/utils/Utils.ts
=> Always do HTTP requests sanitization in security helpers.

src/client/ocpp/json/JsonRestChargingStationClient.ts, src/client/websocket/WSClient.ts, src/server/ocpp/json/JsonCentralSystemServer.ts, src/server/ocpp/json/JsonRestWSConnection.ts, src/server/ocpp/json/JsonWSConnection.ts, src/server/ocpp/json/WSConnection.ts, src/types/WebSocket.ts, src/types/configuration/ChargingStationConfiguration.ts, src/types/configuration/WSClientConfiguration.ts, src/utils/Configuration.ts
=> Add support for command local call from REST to OCPP server.

src/integration/charging-station-vendor/ChargingStationVendorFactory.ts, src/integration/charging-station-vendor/ChargingStationVendorIntegration.ts, src/server/rest/service/ChargingStationService.ts
=> Check for all requirements before trying to set a static power

src/server/rest/CentralRestServerService.ts, src/types/Server.ts
=> Remove duplicated server action.

src/migration/MigrationHandler.ts, src/migration/tasks/CleanupSiteAreasTask.ts, src/server/ocpp/utils/OCPPUtils.ts
The filter property on the database operation may be extended or changed.
=> Clean up site areas and check for id before saving site area

src/assets/server/ocpp/schemas/boot-notification-request.json, src/assets/server/ocpp/schemas/status-notification-request.json
=> Validation: serial number are optional in the OCPP spec.

src/assets/server/ocpp/schemas/boot-notification-request.json, src/assets/server/ocpp/schemas/status-notification-request.json, src/assets/server/ocpp/schemas/stop-transaction-request-15.json, src/assets/server/ocpp/schemas/stop-transaction-request-16.json
=> Schema validation: allow optional fields to be there but empty.

.eslintrc.json, src/server/rest/validation/SchemaValidator.ts
=> Refine eslint rules.

src/server/ocpp/json/WSConnection.ts, src/server/rest/service/security/RegistrationTokenSecurity.ts
Avoid crash on various firmware.
=> Ensure OCPP error messages always follow the OCPP specs.

src/client/ocpp/soap/SoapChargingStationClient.ts, src/integration/charging-station-vendor/ChargingStationVendorIntegration.ts, src/server/ocpp/json/JsonCentralSystemServer.ts, src/server/ocpp/json/JsonWSConnection.ts, src/server/ocpp/json/WSConnection.ts, src/server/ocpp/json/WSServer.ts, src/server/ocpp/json/services/JsonChargingStationService.ts, src/server/ocpp/services/OCPPService.ts, src/server/rest/service/NotificationService.ts, src/server/rest/service/security/AssetSecurity.ts, src/server/rest/service/security/CarSecurity.ts, src/server/rest/service/security/ChargingStationSecurity.ts, src/server/rest/service/security/CompanySecurity.ts, src/server/rest/service/security/ConnectionSecurity.ts, src/server/rest/service/security/LoggingSecurity.ts, src/server/rest/service/security/NotificationSecurity.ts, src/server/rest/service/security/OCPIEndpointSecurity.ts, src/server/rest/service/security/PricingSecurity.ts, src/server/rest/service/security/SettingSecurity.ts, src/server/rest/service/security/SiteAreaSecurity.ts, src/server/rest/service/security/TenantSecurity.ts, src/server/rest/service/security/TransactionSecurity.ts, src/storage/mongodb/NotificationStorage.ts, src/types/Pricing.ts, src/types/UserNotifications.ts, src/types/requests/HttpOCPIEndpointRequest.ts
=> Security: strong type requests filter.

.github/workflows/unit-tests.yml, build/webpack.dev.js, package.json, src/server/ocpp/utils/OCPPUtils.ts, src/server/rest/service/security/AssetSecurity.ts, src/server/rest/service/security/ChargingStationSecurity.ts, src/server/rest/service/security/PricingSecurity.ts, src/server/rest/validation/ConnectionValidator.ts, src/types/GlobalType.ts, src/utils/Utils.ts, test/api/OCPPCommonTests.ts, test/api/TransactionCommonTests.ts, test/api/client/CentralServerService.ts
=> CI: Add and use a webpack dev build target.

src/integration/car/ev-database/EVDabaseCarIntegration.ts, src/utils/Utils.ts
Prelimimary work, helper methods to do detection by phase are needed.
=> The phases can be rotated, phase usage detection needs to be adjusted accordingly

src/client/ocpi/CpoOCPIClient.ts, src/client/ocpi/EmspOCPIClient.ts, src/server/ocpi/OCPIServer.ts, src/server/ocpi/OCPIUtils.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/CPOLocationsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIMapping.ts, src/types/ocpi/OCPIEvse.ts, src/types/ocpi/OCPILocation.ts
=> OCPI: Fix wrong type attributes in helper because of any type usage.

src/client/ocpi/CpoOCPIClient.ts, src/client/ocpi/OCPIChargingStationClient.ts, src/client/ocpi/OCPIClient.ts, src/integration/asset/AssetIntegration.ts, src/integration/asset/schneider/SchneiderAssetIntegration.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/CredentialsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIMapping.ts, src/types/ocpi/OCPICredential.ts, src/types/ocpi/OCPIEndpoint.ts
=> OCPI: Introduce OCPI credentials type.

src/integration/smart-charging/SmartChargingIntegration.ts
Must be merged with https://github.com/LucasBrazi06/ev-sap-smart-charging/pull/12
=> Add return type on smart charging interface.

src/client/ocpi/CpoOCPIClient.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIMapping.ts, src/server/rest/service/SiteAreaService.ts, src/server/rest/service/SiteService.ts, src/storage/mongodb/SiteAreaStorage.ts, src/storage/mongodb/SiteStorage.ts, src/types/ocpi/OCPIConnector.ts, src/types/ocpi/OCPILocation.ts, src/types/ocpi/OCPITariff.ts
- Fix the current type for DC evse.
- Do not send empty location.
- And opening_times to location.
=> OCPI: Fix a couple of issues:

src/client/ocpi/OCPIClient.ts, src/integration/asset/AssetIntegration.ts, src/integration/billing/BillingIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/integration/charging-station-vendor/ChargingStationVendorFactory.ts, src/integration/charging-station-vendor/ChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/ebee/EbeeChargingStationVendorIntegration.ts, src/integration/smart-charging/SmartChargingIntegration.ts, src/server/rest/service/BillingService.ts, src/server/rest/service/security/BillingSecurity.ts, src/server/rest/service/security/TransactionSecurity.ts, test/api/UserTest.ts
=> Make charging profiles work on Ebee.

src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/EMSPLocationsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/EMSPTokensEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPISessionsService.ts, src/types/ocpi/OCPIStatusCode.ts
=> OCPI: fixlets.

src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/EMSPTariffsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIMapping.ts, src/server/ocpp/services/OCPPService.ts, src/storage/mongodb/SettingStorage.ts
=> OCPI: do not do date filtering until simple princing settings

src/client/ocpi/CpoOCPIClient.ts, src/client/ocpi/EmspOCPIClient.ts, src/client/ocpi/OCPIClient.ts, src/client/websocket/WSClient.ts, src/integration/asset/schneider/SchneiderAssetIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/integration/car/ev-database/EVDabaseCarIntegration.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/CPOCommandsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/CredentialsEndpoint.ts, src/server/odata/client/BaseApi.ts, src/server/rest/service/AuthService.ts, src/utils/Utils.ts, test/api/client/utils/BaseApi.ts
=> Add exponential backoff retries logic to most of connection requests. 

src/integration/asset/schneider/SchneiderAssetIntegration.ts, src/server/odata/client/AuthenticatedApi.ts, src/server/odata/client/BaseApi.ts, test/api/client/AuthenticationApi.ts, test/api/client/utils/BaseApi.ts
=> Disable retries at login phase.

src/client/ocpi/CpoOCPIClient.ts, src/client/ocpi/EmspOCPIClient.ts, src/client/ocpi/OCPIClient.ts, src/integration/asset/schneider/SchneiderAssetIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/integration/car/ev-database/EVDabaseCarIntegration.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/CPOCommandsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/CredentialsEndpoint.ts, src/server/ocpp/validation/OCPPValidation.ts, src/server/odata/client/BaseApi.ts, src/server/rest/service/AuthService.ts, src/utils/AxiosFactory.ts, test/api/client/utils/BaseApi.ts
=> Consolidate axios instanciation and setup in an object factory class.

src/scheduler/tasks/CheckOfflineChargingStationsTask.ts, src/storage/mongodb/ChargingStationStorage.ts
I hope that this is the right approach.  Has to be tested on site.
=> Check if charging station is offline before sending notification

src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIMapping.ts, src/server/ocpp/services/OCPPService.ts, src/server/rest/service/TransactionService.ts, src/storage/mongodb/ConsumptionStorage.ts
Last 5 consumption's are currently determined by an array function. 
Another possibility would be to get it through the database request, by modifying the getConsumptions method. 
Let me know if any changes are needed.
=> Notification avoid checking the inactivity to send the end of charge notification

src/integration/charging-station-vendor/ChargingStationVendorFactory.ts, src/integration/charging-station-vendor/atess/AtessChargingStationVendorIntegration.ts, src/types/ChargingStation.ts
=> Add ATESS vendor for smart charging support.

src/integration/charging-station-vendor/ChargingStationVendorFactory.ts, src/types/ChargingStation.ts
=> Add MENNEKES charging stations support.

src/authorization/Authorizations.ts, src/storage/mongodb/OCPPStorage.ts, src/utils/Utils.ts, test/api/CarTest.ts, test/api/UserTest.ts, test/api/context/TenantContext.ts
+ Comments refinement in tag management;
+ Use server action on error in isTagIDAuthorizedOnChargingStation();
+ Typing.
=> Small cleanups

src/utils/AxiosFactory.ts
=> Add sensible default retry conditions to AxiosFactory.

src/server/ocpp/services/OCPPService.ts, src/server/ocpp/utils/OCPPUtils.ts
=> Add support for L{1,2,3}-N phase specification in relevant metervalues

.gitignore
=> .gitignore: add package-lock.json.

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/unit-tests.yml
=> Fix GitHub CI after package-lock.json removal.

src/utils/AxiosFactory.ts
=> Axios: Fix TypeError: Cannot read property 'status' of undefined

src/utils/Logging.ts
That will avoid to clutter the master tenant logs with error message.
=> Logging: perform a simple case insensitive search and replace on string log  message for sensitive data.

.vscode/launch.json, package.json
=> Fix debug script.

src/client/ocpp/soap/SoapChargingStationClient.ts, src/server/ocpp/json/WSConnection.ts, src/server/rest/CentralRestServerAuthentication.ts, src/types/Server.ts
=> Untangle password reset from charging station reset.

src/integration/charging-station-vendor/ChargingStationVendorFactory.ts, src/integration/charging-station-vendor/abb/AbbChargingStationVendorIntegration.ts, src/server/ocpp/utils/OCPPUtils.ts, test/api/context/TenantContext.ts
=> Add ABB charging station vendor to power limitation.

.pipeline/config.yaml, package.json, src/types/ChargingStation.ts
Require a major and totally untested firebase update.
Handle with care.
=> Security: fix node-forge related issues.

src/server/rest/router/GlobalRouter.ts, src/server/rest/router/api/TenantRouter.ts, src/server/rest/router/auth/AuthRouter.ts, src/server/rest/router/doc/SwaggerRouter.ts, src/server/rest/router/util/UtilRouter.ts, src/types/Server.ts
+ Lower case only,
+ More standard auth enpoints name.
That will lead to duplication during the transition.
=> RESTful API: define specific action for the API.

README.md, src/authorization/Authorizations.ts, src/client/ocpi/EmspOCPIClient.ts, src/client/ocpp/json/JsonChargingStationClient.ts, src/client/ocpp/json/JsonRestChargingStationClient.ts, src/integration/billing/BillingIntegration.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/EMSPTokensEndpoint.ts, src/server/ocpp/json/JsonCentralSystemServer.ts, src/server/ocpp/json/WSConnection.ts, src/server/ocpp/services/OCPPService.ts, src/server/rest/v1/router/GlobalRouter.ts, src/server/rest/v1/service/AuthService.ts, src/server/rest/v1/service/LoggingService.ts, src/server/rest/v1/service/NotificationService.ts, src/server/rest/v1/service/TenantService.ts, src/server/rest/v1/service/UserService.ts, src/server/rest/v1/service/UtilsService.ts, src/utils/Utils.ts, test/api/ocpp/json/OCPPJsonService16.ts
=> Consistent naming for REST endpoints.

src/integration/charging-station-vendor/ChargingStationVendorIntegration.ts, src/server/ocpp/services/OCPPService.ts, src/server/ocpp/utils/OCPPUtils.ts, src/server/rest/v1/service/ChargingStationService.ts, src/storage/mongodb/AssetStorage.ts, src/storage/mongodb/BillingStorage.ts, src/storage/mongodb/CarStorage.ts, src/storage/mongodb/ChargingStationStorage.ts, src/storage/mongodb/CompanyStorage.ts, src/storage/mongodb/ConsumptionStorage.ts, src/storage/mongodb/LoggingStorage.ts, src/storage/mongodb/NotificationStorage.ts, src/storage/mongodb/OCPIEndpointStorage.ts, src/storage/mongodb/OCPPStorage.ts, src/storage/mongodb/RegistrationTokenStorage.ts, src/storage/mongodb/SettingStorage.ts, src/storage/mongodb/SiteAreaStorage.ts, src/storage/mongodb/SiteStorage.ts, src/storage/mongodb/TenantStorage.ts, src/storage/mongodb/TransactionStorage.ts, src/storage/mongodb/UserStorage.ts, src/utils/Constants.ts, src/utils/Logging.ts, src/utils/Utils.ts
+ Rename cloneJsonDocument to cloneObject
=> Use the same rounding helper everywhere.

src/scheduler/tasks/CheckChargingStationTemplateTask.ts, test/api/context/ChargingStationContext.ts
=> Ensure the static limitation value is never over the connector value.

src/migration/MigrationHandler.ts, src/scheduler/tasks/CheckAndComputeSmartChargingTask.ts, src/scheduler/tasks/LoggingDatabaseTableCleanupTask.ts, src/scheduler/tasks/SynchronizeRefundTransactionsTask.ts, src/scheduler/tasks/ocpi/OCPICheckCdrsTask.ts, src/scheduler/tasks/ocpi/OCPICheckLocationsTask.ts, src/scheduler/tasks/ocpi/OCPICheckSessionsTask.ts, src/scheduler/tasks/ocpi/OCPIGetCdrsTask.ts, src/scheduler/tasks/ocpi/OCPIGetLocationsTask.ts, src/scheduler/tasks/ocpi/OCPIGetSessionsTask.ts, src/scheduler/tasks/ocpi/OCPIGetTokensTask.ts, src/scheduler/tasks/ocpi/OCPIPatchLocationsTask.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/CPOCommandsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIMapping.ts, src/server/ocpp/json/WSServer.ts, src/storage/mongodb/MongoDBStorage.ts, src/utils/Logging.ts, src/utils/Utils.ts
=> OCPI: Workaround Gireve mis-interpretation of the specification

src/server/ocpp/json/WSConnection.ts, src/utils/Logging.ts
=> Unit conversion fix.

src/scheduler/tasks/ocpi/OCPIGetLocationsTask.ts, src/scheduler/tasks/ocpi/OCPIPushLocationsTask.ts, src/utils/Utils.ts
=> OCPI: fix scheduler task config handling.

.vscode/launch.json, .vscode/tasks.json, package-lock.json, package.json, src/utils/Utils.ts
=> Fix chargebox id regexp. 

src/server/ocpp/json/JsonCentralSystemServer.ts, src/server/ocpp/json/WSConnection.ts, src/server/ocpp/services/OCPPService.ts, test/api/ocpp/json/OCPPJsonService16.ts
=> Typing and cleanups

src/utils/AxiosFactory.ts, src/utils/Configuration.ts
Make Configuration self-contained
=> Fix circular dependency with mocha and Configuration.

src/migration/tasks/DeleteChargingStationPropertiesTask.ts, src/migration/tasks/RenameChargingStationPropertiesTask.ts, src/server/ocpp/validation/OCPPValidation.ts, src/server/rest/v1/validator/ConnectionValidator.ts
=> Fix method shadowing in inherited objects.

src/migration/tasks/DeleteChargingStationPropertiesTask.ts, src/migration/tasks/RenameChargingStationPropertiesTask.ts
=> Force re-run of migration tasks.

src/utils/I18nManager.ts
=> Fix moment locales list.

src/server/ocpi/OCPIUtils.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIMapping.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPISessionsService.ts, src/server/ocpp/utils/OCPPUtils.ts, src/server/odata/odata-entities/ODataTransactions.ts, src/server/rest/v1/service/AuthService.ts, src/server/rest/v1/service/StatisticService.ts, src/server/rest/v1/service/TransactionService.ts, src/storage/mongodb/TransactionStorage.ts, src/utils/I18nManager.ts, src/utils/Utils.ts, test/api/OCPPCommonTests.ts
=> Remove truncation usage for rounding numbers.

docker/config-standalone.json, docker/config.json, package-lock.json, package.json
=> Remove bson-ext dependency.

src/server/ocpp/json/JsonWSConnection.ts, src/storage/mongodb/ChargingStationStorage.ts, test/api/ocpp/json/OCPPJsonService16.ts, test/api/ocpp/soap/OCPPSoapService15.ts
=> Fix lastSeen update: pass the right id.

src/server/ocpp/services/OCPPService.ts
Workaround for charging stations that ignore the value defined in the
boot notification response.
=> Set the standard OCPP param heartbeat interval value at boot notification.

src/integration/charging-station-vendor/ChargingStationVendorIntegration.ts, src/scheduler/tasks/CheckChargingStationTemplateTask.ts, src/server/ocpp/services/OCPPService.ts, src/server/ocpp/utils/OCPPUtils.ts, src/types/ChargingStation.ts
=> Templates: fix not matched sections logic.

src/server/ocpp/utils/OCPPUtils.ts, test/api/OCPPCommonTests.ts
Fix bug with float sum in node.
Same issue in [this link](https://stackoverflow.com/questions/12511057/float-sum-with-javascript).
=> Fix ocpp pricing to only 3 decimal degits

src/server/ocpp/json/JsonCentralSystemServer.ts, src/server/ocpp/json/JsonRestWSConnection.ts
=> Use the client factory everywhere.

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/unit-tests.yml, package-lock.json, package.json, src/server/ocpp/json/JsonRestWSConnection.ts, src/server/ocpp/json/JsonWSConnection.ts
+ Fix error handling at handshake for nodejs 12.x: https://github.com/websockets/ws/releases/tag/7.4.1
+ Prepare CI for current nodejs LTS (14.x)
=> Update ws package to latest

src/server/ocpp/json/JsonCentralSystemServer.ts
=> Fix calling method on undefined.

src/scheduler/tasks/CheckChargingStationTemplateTask.ts
=> Force git to keep empty directories for components export.

src/scheduler/tasks/CheckChargingStationTemplateTask.ts, src/utils/Utils.ts
=> Fix initial static limitation value setting null check.

package-lock.json, package.json, src/client/ocpp/soap/SoapChargingStationClient.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/CPOTokensEndpoint.ts, src/server/ocpp/json/JsonWSConnection.ts, src/server/rest/v1/service/RegistrationTokenService.ts, src/types/RegistrationToken.ts, src/types/configuration/Configuration.ts, src/types/configuration/JsonEndpointConfiguration.ts, src/types/configuration/WSDLEndpointConfiguration.ts, src/utils/Configuration.ts, src/utils/Utils.ts
=> Add OCPP backend configuration support for secure and insecure URIs

src/server/ocpp/json/JsonCentralSystemServer.ts, src/server/ocpp/json/WSConnection.ts, src/server/ocpp/soap/SoapCentralSystemServer.ts, src/types/WebSocket.ts, src/types/ocpp/OCPPServer.ts, src/utils/Utils.ts, test/api/context/TenantContext.ts
=> Cleanup logic in OCPP server URIs building.

src/integration/car/CarIntegration.ts, src/migration/tasks/InitialCarImportTask.ts
Only generate the images's hash when all the images downloaded successfully (hash: null is a flag of an incomplete import)
=> Car images sync

src/server/rest/v1/service/TransactionService.ts
To specify the timezone and time of the charging station only in the exported csv file
=> Added 5 columns to the sessions / export csv

src/client/ocpi/OCPIClient.ts, src/client/ocpp/json/JsonRestChargingStationClient.ts, src/exception/OcppError.ts, src/server/ocpi/OCPIUtils.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/CPOCommandsEndpoint.ts, src/server/ocpp/json/JsonRestWSConnection.ts, src/server/ocpp/json/JsonWSConnection.ts, src/server/ocpp/json/WSConnection.ts, src/server/ocpp/json/WSServer.ts, src/types/ocpp/OCPPCommon.ts, src/utils/Logging.ts, test/api/UnitTestTemplate.ts, test/api/context/ContextBuilderRunner.ts, test/api/ocpp/json/OCPPJsonService16.ts
=> Type and fix OCPP error handling.

src/client/ocpi/CpoOCPIClient.ts, src/server/ocpi/OCPIUtils.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/CPOCommandsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIMapping.ts
It's a breaking change that should not be merged until the uid change are
sorted out with Gireve.
OICP code must port the id and uid generation fix made here.
=> Build consistent EVSE id and uid at all level.

src/utils/Configuration.ts
=> Fixlet to MongoDB SCP service regexp.

src/authorization/Authorizations.ts, src/client/ocpi/CpoOCPIClient.ts, src/server/rest/v1/service/ChargingStationService.ts
=> OCPI: fix authorization on Gireve.

src/integration/charging-station-vendor/ChargingStationVendorFactory.ts, src/integration/charging-station-vendor/ChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/evbox/EVBOXChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/innogy/InnogyChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/keba/KebaChargingStationVendorIntegration.ts, src/migration/tasks/UpdateChargingStationStaticLimitationTask.ts, src/server/rest/v1/service/UtilsService.ts, src/types/ChargingStation.ts, src/utils/Utils.ts
=> Add Innogy, Keba charging stations vendor + add support for units for static limitation

src/authorization/Authorizations.ts
=> Handled nullified transaction argument in isTagIDAuthorizedOnChargingStation()

README.md
=> README: add missed quote at cut&paste.

.gitmodules
I have added the private repo as a submodule for SCP configurations.
=> scp config submodule for deployment is added

src/server/ocpp/json/WSServer.ts
=> Return meaningful HTTP status code and message if the WS server issue a

src/server/rest/CentralRestServer.ts, src/server/rest/v1/service/ChargingStationService.ts
=> Do not log an error on a successful unlock connector command.

src/integration/charging-station-vendor/ChargingStationVendorFactory.ts, src/integration/charging-station-vendor/circontrol/CIRCONTROLChargingStationVendorIntegration.ts, src/types/ChargingStation.ts
This adds backend support for CIRCONTROL Constructor Templates
[Asana Task A55](https://app.asana.com/0/0/1199549758947437/f)
=> adding circontrol template support

.vscode/launch.json, src/notification/NotificationHandler.ts
=> Refine vscode debugging

src/assets/server/rest/v1/schemas/auth/auth-reset-password.json, src/server/rest/v1/service/AuthService.ts, src/utils/Utils.ts, test/api/AuthenticationTest.ts, test/api/client/AuthenticationApi.ts, test/api/client/utils/BaseApi.ts
Handle reset password + verify user account properly (new tenant) + removed check of strong password (dups) + Fixed Unit Tests
=> Fixed reset password + verify user account

test/api/BillingTest.ts, test/api/context/BillingContext.ts
minor changes - to make it possible to start billing tests
=> billing-ut - database initialize properly

docker/config-standalone.json, docker/config.json, src/scheduler/SchedulerManager.ts, src/scheduler/tasks/ocpi/OCPIPushEVSEStatusesTask.ts, src/scheduler/tasks/ocpi/OCPIPushLocationsTask.ts, src/types/Server.ts, src/types/TaskConfig.ts
I created this Pull Request to investigate if the PushLocationsTask only pushes the EVSE Statuses and not all EVSEs / Locations
=> Check OCPI PushLocationsTask

src/server/rest/v1/service/AuthorizationService.ts, src/storage/mongodb/LoggingStorage.ts, src/storage/mongodb/OCPPStorage.ts, src/types/Server.ts, src/types/Setting.ts, src/types/requests/HttpByIDRequest.ts, src/types/requests/HttpChargingStationRequest.ts, src/types/requests/HttpTenantRequest.ts
=> Linter fixes and submodules update.

src/storage/mongodb/PerformanceStorage.ts, src/types/Performance.ts, src/utils/Logging.ts, src/utils/Utils.ts
=> Add current process memory and CPU usage to performance record.

src/storage/mongodb/PerformanceStorage.ts, src/types/Performance.ts, src/utils/Utils.ts
=> Also track OS CPUs usage and information in performance record.

src/server/rest/v1/service/UserService.ts, src/server/rest/v1/service/security/AssetSecurity.ts, src/server/rest/v1/service/security/BillingSecurity.ts, src/server/rest/v1/service/security/ChargingStationSecurity.ts, src/server/rest/v1/service/security/CompanySecurity.ts, src/server/rest/v1/service/security/SettingSecurity.ts, src/server/rest/v1/service/security/SiteAreaSecurity.ts, src/server/rest/v1/service/security/SiteSecurity.ts, src/server/rest/v1/service/security/TransactionSecurity.ts, src/server/rest/v1/service/security/UserSecurity.ts, src/server/rest/v1/service/security/UtilsSecurity.ts, src/utils/Utils.ts
also changed the admin plate id part as when it was empty it was not updated
will avoid null values to be not taken in account (didn't tested every case for example assets)
=> added objectHasProperty to ifs in security files

src/integration/billing/stripe/StripeBillingIntegration.ts, src/storage/mongodb/BillingStorage.ts, src/types/Billing.ts
last payment failure info is now kept in the billing invoice!
=> Stripe - keep track of the last payment failure

docker/config-standalone.json, docker/config.json, src/assets/config-template-https.json, src/storage/mongodb/UserStorage.ts, src/utils/Configuration.ts
=> Deprecate configuration keys

src/integration/billing/stripe/StripeBillingIntegration.ts, src/server/rest/v1/service/BillingService.ts, test/api/BillingStripeIntegrationTest.ts, test/api/BillingStripeTestData.ts
added tests assign/detach/verify
added missing next()s
repaired getTaxes()
=> Payment method (pm) polish

src/server/ExpressTools.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIMapping.ts
=> JSDoc fixlets.

src/integration/billing/BillingIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/server/rest/v1/service/BillingService.ts, src/server/rest/v1/service/security/BillingSecurity.ts, src/types/Billing.ts, src/types/requests/HttpBillingRequest.ts, test/api/BillingStripeTestData.ts
- BillingPaymentMethodResult has been removed
- HttpBillingRequest has been cleanup - Trying to apply the same logic for all endpoints (still not clear for the deletePaymentMethod)
- removed the attempt to sanitize the request.user ==> userToken 
- getPaymentMethods - returns Promise<BillingPaymentMethod[]>
- removed console.log of operation results
- removed some TODO comments
- added call to Logging.logSecurityInfo() when deleting payment method
=> Billing - stripe - API cleanup

src/scheduler/tasks/CheckAndComputeSmartChargingTask.ts, src/server/ocpp/services/OCPPService.ts, src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/SiteAreaService.ts, test/api/LockingTest.ts
=> Use lock with timeout for smart charging.

src/server/rest/v1/service/CompanyService.ts, src/types/DataResult.ts
Add canCreate on Companies list.
=> Company authorization update

src/server/rest/v1/service/AuthorizationService.ts, src/server/rest/v1/service/CompanyService.ts, src/types/DataResult.ts
Refactor code that adds canCreate flag on companies list root.
Add CompanyDataResult interface.
=> Refactor Company canCreate.

src/server/rest/v1/service/AuthorizationService.ts, src/server/rest/v1/service/SiteService.ts, src/types/DataResult.ts
Same approach as for Company entity.
=> Add canCreate on sites root.

src/server/rest/v1/service/AuthorizationService.ts
Backend check to enforce we cannot modify entities with issuer=false. 
Q: Is this check enough?
=> Add issuer check for company & site.

src/assets/server/rest/v1/schemas/common/common.json, src/integration/billing/stripe/StripeHelpers.ts, src/scheduler/tasks/CheckUserAccountInactivityTask.ts, src/scheduler/tasks/SynchronizeBillingInvoicesTask.ts, src/scheduler/tasks/SynchronizeBillingUsersTask.ts, test/api/SecurityTest.ts
=> Fix tenant subdomain emptyness ut

src/authorization/Authorizations.ts, src/server/rest/CentralRestServerService.ts, src/server/rest/v1/service/AssetService.ts, src/server/rest/v1/service/AuthorizationService.ts, src/server/rest/v1/service/BillingService.ts, src/server/rest/v1/service/CarService.ts, src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/CompanyService.ts, src/server/rest/v1/service/NotificationService.ts, src/server/rest/v1/service/OCPIEndpointService.ts, src/server/rest/v1/service/OICPEndpointService.ts, src/server/rest/v1/service/RegistrationTokenService.ts, src/server/rest/v1/service/SettingService.ts, src/server/rest/v1/service/SiteAreaService.ts, src/server/rest/v1/service/SiteService.ts, src/server/rest/v1/service/TagService.ts, src/server/rest/v1/service/TenantService.ts, src/server/rest/v1/service/TransactionService.ts, src/server/rest/v1/service/UserService.ts, src/server/rest/v1/service/UtilsService.ts, src/server/rest/v1/validator/ChargingStationValidator.ts, src/storage/mongodb/ChargingStationStorage.ts
Add authorization check on getChargingStation
=> Fix getChargingStation by id

src/server/ocpp/utils/OCPPUtils.ts
=> Factor out connector amperage limit code.

src/server/ocpp/utils/OCPPUtils.ts
=> Log when a charging station have a template and is manually configured.

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/unit-tests.yml, CONTRIBUTING.md, README.md, package.json, src/authorization/AuthorizationsDefinition.ts, src/client/ocpp/soap/SoapChargingStationClient.ts, src/server/ocpp/services/OCPPService.ts, src/server/rest/CentralRestServerService.ts, src/server/rest/v1/service/SiteAreaService.ts, src/server/rest/v1/service/UserService.ts, src/start.ts, src/utils/Utils.ts, test/api/OCPPCommonTests.ts, test/api/SmartChargingTest.ts, test/api/context/ContextDefinition.ts, test/api/context/ContextProvider.ts, test/api/context/StatisticsContext.ts, test/api/ocpp/json/OCPPJsonService16.ts, test/factories/ChargingStationFactory.ts
+ Remove useless eslint disable per line;
+ Type a bit ut;
+ Documentation fixes; 
+ Github actions cleanups.
=> Code cleanups:

package-lock.json, package.json
=> Update sharp to 0.28.1

src/authorization/Authorizations.ts, src/client/oicp/CpoOICPClient.ts, src/server/ocpp/services/OCPPService.ts, src/server/ocpp/utils/OCPPUtils.ts, test/api/ocpp/soap/OCPPSoapService15.ts
=> Spell fixes.

src/types/Setting.ts
very simple fix - duplicated stuff removed
=> CryptoSetting - duplicated def removed

src/server/rest/v1/service/ChargingStationService.ts
Fixed check of empty charge points with utils method in manual configuration context
=> Fixed refactoring check for empty cps

src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/LoggingService.ts, src/server/rest/v1/service/StatisticService.ts, src/server/rest/v1/service/TransactionService.ts, src/server/rest/v1/service/UserService.ts
- used .join() + .map()
- put double quote and escaped double quotes in text to keep commas inside text
- handled null headers to still have CRLF
- for charging stations, logs, transactions, statistics and users
=> modified export csv handling

test/api/SiteAreaOrgTest.ts
Some data was not cleared after the tests & this was causing the issue.
=> Fix in org unit tests

src/server/ocpp/utils/OCPPUtils.ts, src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/LoggingService.ts, src/server/rest/v1/service/StatisticService.ts, src/server/rest/v1/service/TransactionService.ts, src/server/rest/v1/service/UserService.ts, src/utils/Utils.ts, test/api/OCPPAllVersionsTest.ts
=> Ensure amperage limit value is at least the min per phase * number of

src/utils/Utils.ts
=> Set a default min amperage limit value if none are found (take 2).

src/server/ocpp/utils/OCPPUtils.ts, src/server/rest/v1/service/UtilsService.ts, src/utils/Utils.ts
Take 3 and hopefully the latest. 
=> Set default amperage limit to the charging station value.

src/integration/charging-station-vendor/ChargingStationVendorFactory.ts, src/integration/charging-station-vendor/dbtcev/DBTCEVChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/evmeter/EVMeterChargingStationVendorIntegration.ts, src/types/ChargingStation.ts
=> Add DBT-CEV and EVMeter to charging station vendor.

src/server/rest/v1/service/TagService.ts, src/server/rest/v1/service/UserService.ts
changed "mimetype" check to "ending with .csv" check
=> Tag import fix mimtype check

.xmake.cfg, package.json
=> Merge SAP GitHub changes.

src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/LoggingService.ts, src/server/rest/v1/service/StatisticService.ts, src/server/rest/v1/service/TransactionService.ts, src/server/rest/v1/service/UserService.ts, test/api/TestUtils.ts
+ changed .replace to delete only double quotes that are at the beginning and the end of the value we want to put in csv and we keep the one inside the text if any
=> Statistic ut fixes

src/storage/mongodb/ConsumptionStorage.ts, test/api/BillingStripeTestData.ts
=> Deduplicate await statement.

src/server/ocpp/utils/OCPPUtils.ts, test/api/OCPPAllVersionsTest.ts, test/api/OCPPCommonTests.ts, test/api/context/ChargingStationContext.ts
Update to the fix + new Unit Tests
The previous fix didn't take into account the previous data in the transaction.
This is now fixed
=> Eichrecht : Signed Data is not correctly transmited with some systems

src/storage/mongodb/TransactionStorage.ts
Wrong feedback when billing is OFF
=> billing - do not show sessions in error when billing is OFF

src/server/rest/v1/service/AuthService.ts, src/server/rest/v1/service/UtilsService.ts
=> Separate user update and creation password check

src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/LoggingService.ts, src/server/rest/v1/service/StatisticService.ts, src/server/rest/v1/service/TransactionService.ts, src/server/rest/v1/service/UserService.ts, src/utils/Utils.ts
added utils to handle double quote replacement
deleted cypher for user.id
=> created method for double quotes handling

README.md, docker/ev_server-standalone.Dockerfile, docker/ev_server.Dockerfile
=> uWebSockets.js require git at npm install

src/client/ocpi/OCPIClient.ts, src/client/ocpi/OCPIClientFactory.ts, src/client/ocpp/json/JsonChargingStationClient.ts, src/server/MicroWsUtils.ts, src/server/ServerUtils.ts, src/server/ocpi/OCPIServer.ts, src/server/ocpp/json/JsonRestWSConnection.ts, src/server/ocpp/json/JsonWSConnection.ts, src/server/ocpp/json/WSConnection.ts, src/server/ocpp/services/OCPPService.ts, src/server/ocpp/validation/OCPPValidation.ts, src/server/rest/v1/service/ConnectionService.ts, src/server/rest/v1/service/SessionHashService.ts, src/storage/mongodb/OCPIEndpointStorage.ts
=> Linter silencing and cleanups.

src/types/configuration/WSClientConfiguration.ts, src/utils/Configuration.ts, test/api/BillingTest.ts, test/api/client/utils/BaseApi.ts, test/config.js
=> Untangle server configuration from ut one some more: axios HTTP client.

src/authorization/AuthorizationsDefinition.ts, src/server/rest/v1/service/BillingService.ts, src/types/Server.ts, test/api/BillingTest.ts
Hidding features hat are not useful:
- Sync Invoices
- Create Invoice from transaction in Error
- Authorization commented out
+ Minor constant cleanup
=> Billing - hide unused features

src/integration/billing/stripe/StripeBillingIntegration.ts, test/api/BillingStripeTestData.ts
=> Billing - minor fixes for beta

src/server/MicroWsUtils.ts, src/server/ocpi/OCPIUtils.ts, src/server/ocpp/json/JsonCentralSystemServer.ts, src/server/ocpp/json/WSServer.ts, src/server/odata/ODataServerFactory.ts, src/server/odata/odata-entities/AbstractODataEntities.ts, src/server/odata/odata-entities/ODataBootNotifications.ts, src/server/odata/odata-entities/ODataChargingStations.ts, src/server/odata/odata-entities/ODataCompanies.ts, src/server/odata/odata-entities/ODataConnectors.ts, src/server/odata/odata-entities/ODataSiteAreas.ts, src/server/odata/odata-entities/ODataSites.ts, src/server/odata/odata-entities/ODataStatusNotifications.ts, src/server/odata/odata-entities/ODataTransactions.ts, src/server/odata/odata-entities/ODataUsers.ts, src/server/odata/odata-schema/ODataSchema.ts, src/server/rest/CentralRestServer.ts, src/server/rest/v1/service/UserService.ts, src/start.ts, src/storage/mongodb/AsyncTaskStorage.ts, src/storage/mongodb/CarStorage.ts, src/storage/mongodb/DatabaseUtils.ts, src/storage/mongodb/OCPPStorage.ts, src/storage/mongodb/OICPEndpointStorage.ts
=> Encapsulate some more the WS server logic in its own class

package-lock.json, package.json, src/client/ocpi/CpoOCPIClient.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts, src/server/oicp/oicp-services-impl/oicp-2.3.0/OICPMapping.ts
=> Apply security updates.

src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts
=> OCPI: opening times need to disable twentyfourseven if hours are

src/authorization/AuthorizationsDefinition.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/server/ocpp/utils/OCPPUtils.ts, src/utils/FeatureToggles.ts, test/api/BillingStripeTestData.ts, test/api/BillingTest.ts
Activating all features for our first dead line:
- All features are ON
- Granting back BILLING permissions to BASIC users
- Checking for Payment Method at transaction start (thorw an exception if nop PM)
- UT Billing - some test adaptation
=> Billing - all feature toggles on

src/authorization/AuthorizationsDefinition.ts, src/server/rest/v1/service/AuthorizationService.ts, src/types/Authorization.ts
Add `canExportOCPPParams`  and `canGenerateQrCode` on Site and SiteArea entities.
=> Missing flags

src/storage/mongodb/SettingStorage.ts
bug fixed on initial billing settings values
=> billing settings - handle properly initial values

src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts
=> Add customers default tariff_id

package-lock.json, package.json, src/storage/mongodb/MongoDBStorage.ts, src/types/ocpp/OCPPCommon.ts, tsconfig.json
=> Reduce a bit the bundle size

src/server/ocpp/utils/OCPPUtils.ts
=> Revert boot notification status check

src/server/ocpp/json/JsonWSConnection.ts
=> Revert boot notification registration check.

src/server/rest/v1/router/api/ChargingStationRouter.ts
=> Hotfix: Add backward compatibility on REST endpoints for the mobile app

src/server/rest/v1/router/api/ChargingStationRouter.ts, src/server/rest/v1/service/ChargingStationService.ts
handle call from all endpoints.
=> Push down backward compatibility code inside the service method to

src/server/rest/v1/router/api/ChargingStationRouter.ts
=> Push down backward compatibility code inside the service method to handle call from all endpoints.

src/authorization/AuthorizationsDefinition.ts, src/authorization/dynamic-data-source/AssignedSitesDynamicAuthorizationDataSource.ts, src/authorization/dynamic-data-source/SitesAdminDynamicAuthorizationDataSource.ts, src/server/rest/v1/service/AuthorizationService.ts, src/server/rest/v1/service/SiteService.ts, src/server/rest/v1/service/UtilsService.ts, src/types/Authorization.ts, test/api/CompanyOrgTest.ts
Here are the adjustments that I made to Sites auth after going through the whole flow for SiteAreas.
In case you agree with everything I did for SiteArea, these changes should also be fine, but I leave it up to you to check and decide. It's mostly refactoring.
=> Site auth adjustments

src/integration/asset/schneider/SchneiderAssetIntegration.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts, src/server/ocpp/services/OCPPService.ts, src/server/ocpp/utils/OCPPUtils.ts
=> Fix consumption instantAmps calculation from metervalues

src/authorization/Authorizations.ts, src/authorization/AuthorizationsDefinition.ts, src/server/rest/v1/router/api/BillingRouter.ts, src/server/rest/v1/service/BillingService.ts, src/server/rest/v1/service/security/BillingSecurity.ts, src/storage/mongodb/BillingStorage.ts, src/types/Server.ts, src/types/requests/HttpBillingRequest.ts
- /invoices works & implemented in dashboard
- /invoices/:invoiceid works & implemented in dashboard but never used yet
- /invoices/:invoiceid/download needs to be implemented and tested in dahsboard
=> Restful endpoints for invoices - back

test/api/BillingStripeTestData.ts, test/api/BillingTest.ts, test/api/client/BillingApi.ts
Billing Test now using new rest end point for getting Invoices
=> billing - fix tests to consume new endpoints

src/assets/i18n/fr.json, src/integration/billing/stripe/StripeBillingIntegration.ts
Some fixes of the invoice line item details:
- date formatting according to user locale
- energy consumption formatting and precision
- french translation
=> Billing - stripe - bug fix 

.github/workflows/build.yml
=> Add docker image build to GitHub actions

src/server/rest/v1/service/TransactionService.ts, test/api/BillingTest.ts
TransactionStorage.**getTransaction** - Projection has been changed to allow testing whether the invoiceNumber is properly set or not.
=> billing - transaction projection - add invoice number

src/integration/billing/stripe/StripeBillingIntegration.ts, src/utils/FeatureToggles.ts
The periodic billing operation now updates the billing data of each transaction in order to be able to show the final invoice number when looking at the transaction history.
=> periodic billing - update Transaction Billing Data

src/migration/tasks/AddDescriptionToTagsTask.ts, src/migration/tasks/AddVisualIDPropertyToTagsTask.ts, src/migration/tasks/ChangeCryptoKeyTask.ts
Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>Signed-off-by: Jérôme Benoit <jerome.benoit@sap.com>
=> AddVisualIDPropertyToTagsTask: ensure the migration is done on null or empty visualID field.

src/migration/tasks/AddVisualIDPropertyToTagsTask.ts, src/storage/mongodb/MongoDBStorage.ts
=> AddVisualIDPropertyToTagsTask: fix visualID uniqueness per badge

src/integration/billing/BillingIntegration.ts, src/server/rest/v1/service/TransactionService.ts, test/api/BillingTest.ts
utbilling test have been extended to make sure we also check the behavior of the "periodic billing" whcih is supposed to run once a month.
Small changes were necessary to make it testable. For instance, the invoisceStatus has been added to the projection when getting transaction information.
=> Billing test - periodic billing

src/client/ocpp/soap/SoapChargingStationClient.ts, src/server/ocpp/soap/SoapCentralSystemServer.ts, src/server/ocpp/soap/services/SoapCentralSystemService12.ts, src/server/ocpp/soap/services/SoapCentralSystemService15.ts, src/server/ocpp/soap/services/SoapCentralSystemService16.ts
Unfortunatly that code gonna be used in production.
=> OCPP-S: silence linter and improve logs timestamping

src/server/rest/v1/service/BillingService.ts
tiny change to provide the operation result on detachPaymentMethod()
=> billing - detach PM with operation result

src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts
=> OCPI: add operator business details to location

src/server/rest/v1/service/CarService.ts, src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/TagService.ts, src/server/rest/v1/service/TransactionService.ts, src/server/rest/v1/service/UserService.ts
Check authorized flag for all refactored method calls (as Mehdi wonderfully did for canListUsers scanario :) ).
(Looks like the reason I was not able to push commits was because I was not in the github team anymore. If possible, could I stay a team member until [this](https://github.com/sap-labs-france/ev-server/pull/2473) PR gets merged? Just in case it will need adjustments. Thanks!)
=> Check authorized flag everywhere

src/server/rest/v1/service/TagService.ts
modified visual id header
test for name, firstname and email or put ''
=> fix chargex tags import

src/integration/billing/stripe/StripeBillingIntegration.ts
=> billing - une derniere pour le boss

src/server/ocpp/services/OCPPService.ts, src/server/ocpp/utils/OCPPUtils.ts
=> Billing: only process transaction billing if issued by a tenant local user

src/authorization/Authorizations.ts, src/authorization/AuthorizationsDefinition.ts, src/integration/billing/BillingIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/server/rest/v1/router/api/BillingRouter.ts, src/server/rest/v1/service/BillingService.ts, src/types/Authorization.ts, src/types/Server.ts, test/api/BillingStripeTestData.ts, test/api/BillingTestDataCleanupTest.ts, test/api/client/BillingApi.ts
billing - endpoint to clear test data
=> Billing clear test data and reset connection

src/integration/billing/BillingIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/integration/billing/stripe/StripeHelpers.ts, src/server/rest/v1/service/BillingService.ts, src/storage/mongodb/BillingStorage.ts, test/api/BillingStripeTestData.ts
Changed the tenant id to tenant object for Billing storage and associated methods.
=> Billing Storage, changing Tenant ID to object

src/client/ocpp/soap/SoapChargingStationClient.ts, src/integration/charging-station-vendor/ChargingStationVendorFactory.ts, src/integration/charging-station-vendor/joinon/JoinonChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/lafon/LafonChargingStationVendorIntegration.ts, src/server/ocpp/json/JsonWSConnection.ts, src/types/ChargingStation.ts
=> Add charging new station vendors support.

src/integration/billing/stripe/StripeBillingIntegration.ts
minor fix for periodic billing.
The invoice amount shown (on our side) was not the latest one!
=> HOTFIX - periodic billing - refresh data required to get the latest amount

.github/workflows/unit-tests.yml, .vscode/settings.json
switched OFF parallel test runs to avoid unpredictable test results
=> mochatests -  avoid unpredictable test results - parallel: false

src/client/ocpi/EmspOCPIClient.ts, src/server/rest/v1/service/CompanyService.ts, src/server/rest/v1/service/UtilsService.ts, src/storage/mongodb/CompanyStorage.ts
Usage of Tenant Id within CompanyStorage was changed to using tenant object.
=> Change TenantId to Object in CompanyStorage

src/integration/billing/BillingIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts
Some minor changes. 
+ removal of unused methods
=> billing - removed unused method and typed some others

src/server/rest/v1/service/ConnectionService.ts, src/storage/mongodb/ConnectionStorage.ts
Changing Tenant ID to object for Connection storage.
=> Chaning tenant ID to tenant object for Connection Storage

src/integration/charging-station-vendor/ChargingStationVendorFactory.ts, src/integration/charging-station-vendor/abb/AbbChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/atess/AtessChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/circontrol/CIRCONTROLChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/dbtcev/DBTCEVChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/delta/DeltaChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/ebee/EbeeChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/enplus/EnPlusChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/evmeter/EVMeterChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/exadys/ExadysChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/ies/IESChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/ingeteam/IngeteamChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/innogy/InnogyChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/joinon/JoinonChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/lafon/LafonChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/legrand/LegrandChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/sap/SAPLabsFranceChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/schneider/SchneiderChargingStationVendorIntegration.ts, src/integration/charging-station-vendor/wallboxchargers/WallboxChargersChargingStationVendorIntegration.ts
=> Remove duplicated charging station vendor integration classes

src/integration/charging-station-vendor/ChargingStationVendorFactory.ts, src/types/ChargingStation.ts
=> Add Ark charging station vendor support

src/server/rest/v1/service/UserService.ts, src/storage/mongodb/AssetStorage.ts, test/api/BillingTest.ts, test/api/StatisticsTest.ts, test/api/UnitTestTemplate.ts, test/api/context/ContextBuilderRunner.ts
=> UserService.ts: Fix this usage in static method

src/migration/tasks/CleanUpCarUsersWithDeletedUsersTask.ts, src/migration/tasks/CleanUpLogicallyDeletedUsersTask.ts, src/server/ocpp/services/OCPPService.ts, src/server/rest/v1/service/CarService.ts, src/server/rest/v1/service/UserService.ts, src/server/rest/v1/service/UtilsService.ts, src/storage/mongodb/CarStorage.ts
Changing tenant ID to tenant Object for Car Storage and all services that use it.
=> Change tenant ID to object for Car Storage.

src/server/ocpp/services/OCPPService.ts, src/server/ocpp/utils/OCPPUtils.ts, src/server/ocpp/validation/OCPPValidation.ts, src/storage/mongodb/ChargingStationStorage.ts, src/storage/mongodb/OCPPStorage.ts, src/types/ocpp/OCPPServer.ts
=> Add regexp support for charging station vendor in template.

src/async-task/tasks/BillTransactionAsyncTask.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/server/rest/v1/service/BillingService.ts, test/api/BillingStripeTestData.ts, test/api/BillingTest.ts
Minor change to help troubleshooting async billing tasks
=> async billing - some additional consistency checks + logs

src/server/ServerUtils.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts
=> OCPI: Add Properhi tariff_id

src/server/rest/v1/router/api/UserRouter.ts, src/server/rest/v1/service/TagService.ts, src/server/rest/v1/service/UserService.ts
Promises around busboy is to prevent Express to send its default 404 status when the async treatment is not finished yet
=> Fixed 404 error on REST import routes

src/assets/i18n/de.json, src/assets/i18n/en.json, src/assets/i18n/es.json, src/assets/i18n/fr.json, src/assets/i18n/it.json, src/assets/i18n/pt.json, src/integration/billing/stripe/StripeBillingIntegration.ts
Small changes:
- Removal of unused texts!
- Removal of feature toggle
=> billing - invoice item description - cleanup

src/integration/billing/stripe/StripeBillingIntegration.ts, src/utils/FeatureToggles.ts
We do not bill suspicious transactions anymore 
Criteria is so far hardcoded:
- energy consumption lower than 1kWh
- session duration - less than one minute
=> billing - check threshold on stop transaction

src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts
=> OCPI: Customer have choosen the final CS name.

src/client/oicp/CpoOICPClient.ts, src/client/oicp/OICPClient.ts, src/client/oicp/OICPClientFactory.ts, src/scheduler/tasks/oicp/OICPPushEvseDataTask.ts, src/scheduler/tasks/oicp/OICPPushEvseStatusTask.ts, src/server/rest/v1/service/OICPEndpointService.ts, src/server/rest/v1/service/TenantService.ts, src/storage/mongodb/OICPEndpointStorage.ts
Chaning tenant id to tenant Object for OICP endpoint storage.
=> Initial Changes

src/integration/billing/stripe/StripeBillingIntegration.ts, src/utils/FeatureToggles.ts
A feature toggle to prevent customer deletion in stripe
=> billing - prevent STRIPE customers deletion

src/integration/billing/stripe/StripeBillingIntegration.ts
Check added to make sure developpers/testers do not perform actions on a live STRIPE account
=> billing - prevent connection to live account when in DEV and TEST Mode

src/integration/billing/BillingIntegration.ts, src/utils/FeatureToggles.ts, test/api/BillingTest.ts
Minor changes - feature toggles (that were always active) have been removed.
No real impact at runtime!
=> billing - removal of some feature toggles

src/utils/TemplateManager.ts
=> template manager - deep clone template

src/integration/billing/stripe/StripeBillingIntegration.ts
Temporary check specific:
ETE is an external user ;)
=> Billing - temporary demo option

src/async-task/tasks/BillTransactionAsyncTask.ts, src/integration/billing/BillingIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts
=> saveTransactionBillingData is now called

src/authorization/Authorizations.ts, src/client/ocpi/EmspOCPIClient.ts, src/client/oicp/CpoOICPClient.ts, src/integration/charging-station-vendor/ChargingStationVendorIntegration.ts, src/integration/smart-charging/SmartChargingIntegration.ts, src/scheduler/tasks/CheckChargingStationTemplateTask.ts, src/scheduler/tasks/CheckOfflineChargingStationsTask.ts, src/scheduler/tasks/CheckPreparingSessionNotStartedTask.ts, src/scheduler/tasks/ocpi/OCPIPushCdrsTask.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/cpo/CPOCommandsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/emsp/EMSPLocationsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/emsp/EMSPTokensEndpoint.ts, src/server/ocpp/json/JsonRestWSConnection.ts, src/server/ocpp/json/JsonWSConnection.ts, src/server/ocpp/json/WSConnection.ts, src/server/ocpp/services/OCPPService.ts, src/server/ocpp/utils/OCPPUtils.ts, src/server/oicp/OICPUtils.ts, src/server/oicp/oicp-services-impl/oicp-2.3.0/CPORemoteAuthorizationsEndpoint.ts, src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/LoggingService.ts, src/server/rest/v1/service/TransactionService.ts, src/server/rest/v1/service/UtilsService.ts, src/storage/mongodb/ChargingStationStorage.ts, src/storage/mongodb/SiteStorage.ts, test/api/SmartChargingTest.ts
Submodule changes include
1. ev-sap-smart-charging: [PR](https://github.com/sap-labs-france/ev-sap-smart-charging/pull/52)
2. ev-sap-pricing-convergent-charging: [PR](https://github.com/sap-labs-france/ev-sap-pricing-convergent-charging/pull/16)
3. ev-sap-refund-concur: [PR](https://github.com/sap-labs-france/ev-sap-refund-concur/pull/19)
=> Change tenant ID to Object Charging Station

src/async-task/tasks/BillTransactionAsyncTask.ts, src/authorization/Authorizations.ts, src/client/ocpi/CpoOCPIClient.ts, src/client/ocpi/EmspOCPIClient.ts, src/integration/asset/lacroix/LacroixAssetIntegration.ts, src/integration/billing/BillingIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/integration/refund/RefundIntegration.ts, src/integration/refund/dummy/DummyRefundIntegration.ts, src/scheduler/tasks/CheckSessionNotStartedAfterAuthorizeTask.ts, src/scheduler/tasks/SynchronizeRefundTransactionsTask.ts, src/scheduler/tasks/ocpi/OCPIPushCdrsTask.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/cpo/CPOCdrsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/cpo/CPOCommandsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/cpo/CPOSessionsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/emsp/EMSPCdrsEndpoint.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/emsp/EMSPSessionsEndpoint.ts, src/server/ocpp/services/OCPPService.ts, src/server/ocpp/utils/OCPPUtils.ts, src/server/oicp/OICPUtils.ts, src/server/oicp/oicp-services-impl/oicp-2.3.0/CPORemoteAuthorizationsEndpoint.ts, src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/TagService.ts, src/server/rest/v1/service/TransactionService.ts, src/storage/mongodb/TransactionStorage.ts, test/api/context/StatisticsContext.ts
Submodules:
ev-sap-refund-concur : [PR](https://github.com/sap-labs-france/ev-sap-refund-concur/pull/20)
ev-sap-smart-charging : [PR](https://github.com/sap-labs-france/ev-sap-smart-charging/pull/53)
=> Change tenant id to object transaction storage

src/authorization/Authorizations.ts, src/client/ocpi/EmspOCPIClient.ts, src/scheduler/tasks/CheckAndComputeSmartChargingTask.ts, src/server/ocpp/services/OCPPService.ts, src/server/ocpp/utils/OCPPUtils.ts, src/server/rest/v1/service/AssetService.ts, src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/RegistrationTokenService.ts, src/server/rest/v1/service/SiteAreaService.ts, src/server/rest/v1/service/TenantService.ts, src/server/rest/v1/service/UtilsService.ts, src/storage/mongodb/SiteAreaStorage.ts, src/storage/mongodb/SiteStorage.ts, test/api/context/ContextBuilder.ts
Submodules:
[ev-sap-pricing-convergent-charging](https://github.com/sap-labs-france/ev-sap-pricing-convergent-charging/pull/17)
=> Change tenant id to object SiteAreaStorage

src/async-task/tasks/ImportHelper.ts, src/async-task/tasks/UsersImportAsyncTask.ts, src/authorization/Authorizations.ts, src/authorization/dynamic-data-source/SitesAdminDynamicAuthorizationDataSource.ts, src/authorization/dynamic-data-source/SitesOwnerDynamicAuthorizationDataSource.ts, src/client/ocpi/CpoOCPIClient.ts, src/integration/billing/BillingIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/migration/tasks/RestoreDataIntegrityInSiteUsersTask.ts, src/notification/NotificationHandler.ts, src/scheduler/tasks/CheckUserAccountInactivityTask.ts, src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts, src/server/ocpp/services/OCPPService.ts, src/server/oicp/OICPUtils.ts, src/server/rest/v1/service/AuthService.ts, src/server/rest/v1/service/AuthorizationService.ts, src/server/rest/v1/service/BillingService.ts, src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/NotificationService.ts, src/server/rest/v1/service/SessionHashService.ts, src/server/rest/v1/service/TenantService.ts, src/server/rest/v1/service/TransactionService.ts, src/server/rest/v1/service/UserService.ts, src/server/rest/v1/service/UtilsService.ts, src/storage/mongodb/UserStorage.ts, test/api/BillingStripeTestData.ts, test/api/context/ContextBuilder.ts
Submodules:
[ev-sap-refund-concur](https://github.com/sap-labs-france/ev-sap-refund-concur/pull/22)
=> Change Tenant ID to Object User Storage

src/assets/i18n/cz.json
@ClaudeROSSI 
Hello, 
correctly named and validated json file.
=> Added CZ language

src/assets/i18n/cz.json, src/assets/i18n/es.json
Translation in Spanich of the invoice item description
=> billing - invoice item translation ES/CZ

package-lock.json, package.json, src/assets/i18n/fr.json, test/I18nChecker.ts
To test, type the command:
npm run check:i18n
Current issue with content of fr.json!
Not considering cz.json since it is not part of the supported languages.
Let me know if anything has to be reviewed.
=> i18nChecker

src/server/ocpp/utils/OCPPUtils.ts
hotfix - allow authorize when "Enable Access Control" is switched OFF
=> hoxfix - issuer of undefined

build/webpack.common.js, src/server/ocpp/utils/OCPPUtils.ts
- fixed charging-station templates
- fixed handleAuthorize when "Enable Access Control” is switch OFF
=> Hotfix for version 2.4.84

src/assets/server/rest/v1/docs/e-mobility-oas.json, src/assets/server/rest/v1/schemas/tag/tag-update.json
That would be great to remind everyone to update the doc when they add/edit/remove some parameters, or change the response of endpoints. Customer pointed out twice that the documentation doesn't match anymore server requirements on some endpoints
=> Doc > Added missing visualID to documentation

postman/EVSE.postman_collection.json
- Companies
- Transactions
- Assets
- Users
- Tags
- Cars
- Logs
=> Updated postman collections

src/assets/server/rest/v1/schemas/user/users-get.json, src/storage/mongodb/UserStorage.ts
Free text search + NON-technical users is non-effective.
=> technical: and & or filters

package-lock.json, package.json, src/server/MicroWsUtils.ts, src/server/ServerUtils.ts, src/server/ocpi/OCPIServer.ts, src/server/ocpp/json/JsonCentralSystemServer.ts, src/server/ocpp/json/JsonRestWSConnection.ts, src/server/ocpp/json/JsonWSConnection.ts, src/server/ocpp/json/WSConnection.ts, src/server/ocpp/json/WSServer.ts, src/server/ocpp/soap/SoapCentralSystemServer.ts, src/server/ocpp/utils/OCPPUtils.ts, src/server/odata/ODataServer.ts, src/server/oicp/OICPServer.ts, src/server/rest/CentralRestServer.ts, src/start.ts
Reverts sap-labs-france/ev-server#3043
=> Revert "Merge master-qa"

src/client/ocpp/json/JsonRestChargingStationClient.ts, src/client/websocket/WSClient.ts, src/server/ocpp/json/JsonCentralSystemServer.ts
Remove check on 'upgrade' HTTP header not sent by Cahors CS!
=> Fixed wss via REST should have protocol 'rest'

src/server/rest/v1/service/PricingService.ts, src/storage/mongodb/PricingStorage.ts
=> pricing - fixed sort by name + minor changes

src/integration/billing/stripe/StripeBillingIntegration.ts
minor change for troubleshooting purposes
=> billing - keep dimension in item metadata (for troubleshooting)

src/integration/pricing/PricingHelper.ts, src/types/Pricing.ts
just a type definition changed
=> Pricing type definition minor change

src/assets/schemas/pricing/pricing-definition.json, src/integration/pricing/ConsumptionPricer.ts, src/types/Pricing.ts, test/api/BillingTest.ts, test/api/BillingTestHelper.ts
Pricing - restrictions - Additional check to allow defining a tariff for a particular day
=> pricing - restrictions - checkDayOfWeek

src/assets/schemas/pricing/pricing-definition.json, src/integration/pricing/ConsumptionPricer.ts, src/types/Pricing.ts, test/api/BillingTest.ts, test/api/BillingTestHelper.ts
pricing - restriction - capability to define a tariff for a particular time range
=> pricing - restrictions - checkTimeValidity

src/server/rest/v1/service/PricingService.ts
=> pricing - cosmetic changes

src/server/rest/v1/service/PricingService.ts
Additional checks to block a site admin from creating/modifying/deleting tariffs on sites that do not belong to him/her!
=> pricing-check-canMaintainPricingDefinitions

src/migration/tasks/RepairTransactionPricedAtZeroTask.ts
repair v2 for sessions priced a zero and lasting more than 48h hours
=> repair sessions priced at zero

src/server/rest/v1/service/AuthorizationService.ts, src/types/DataResult.ts
- can list sites
- can list site areas
=> Add authorization to determine filter presence

src/integration/pricing/ConsumptionChunkPricer.ts, src/integration/pricing/ConsumptionPricer.ts, src/integration/pricing/simple-pricing/BuiltInPricingIntegration.ts
adding public in front of pricing constructors
=> pricing - minor change - constructor scope

src/integration/billing/stripe/StripeBillingIntegration.ts, src/server/ocpp/services/OCPPService.ts
=> billing + fix transactionUpdated boolean check

src/types/Pricing.ts
missing scope in pricing helper class
=> pricing - add missing scope

src/integration/pricing/PricingEngine.ts
minor change to be on the safe side when billing **prehistoric** sessions!
=> billing - safe billing of "ghost"  sessions

src/integration/billing/stripe/StripeBillingIntegration.ts
Prevent a start transaction when the payment method has expired
=> Billing - check payment method expiration

src/integration/billing/stripe/StripeBillingIntegration.ts
URGENT!
hot fix to make sure the billing data of the last transaction is preserved when computing the extra inactivity
=> billing - preserve session billing data

src/integration/billing/stripe/StripeBillingIntegration.ts, src/migration/MigrationHandler.ts, src/migration/tasks/RepairTransactionBillingData.ts
New migration task: **RepairTransactionBillingData**
It goes thru all invoices generated in January 2022 and updates the corresponding sessions by populating again the billing data.
=> billing - repair transaction billing data task

src/server/rest/v1/service/TransactionService.ts
I need (for displaying tarif details) to  add the 'pricingModel' as a projected field when getting info about a transaction!
=> transaction service - add 'pricingModel' to projection

postman/EVSE.postman_collection.json, src/assets/server/rest/v1/docs/e-mobility-oas.json
=> Anonymized postman collection

package.json, test/api/BillingTest.ts, test/api/BillingTestHelper.ts
minor changes - test conf only
=> jest adaptations

test/api/BillingTest.ts, test/api/BillingTestHelper.ts
=> billing - test issues - troubleshoot timezone related issues

test/factories/AddressFactory.ts
just a change in the create context
=> billing test - force timezone to make it stable

src/integration/billing/BillingIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/storage/mongodb/TransactionStorage.ts, src/utils/Constants.ts
Billing Threshold aligned to the Afirev recommendations
=> billing - afirev - threshold

src/integration/billing/stripe/StripeBillingIntegration.ts
Minor log change - A warning has been removed to avoid confusion!
=> billing - minor log change

src/assets/server/notification/email/body-html.template, src/assets/server/notification/email/body-invoice.template
Links to open-e-mobility web site (in mails and notifications)
=> fix links to open-e-mobility

src/scheduler/tasks/BillPendingTransactionTask.ts
=> Billing - fix inconsistent log

src/integration/billing/stripe/StripeBillingIntegration.ts
Avoid reusing DRAFT invoices with no metadata.
=> billing - better handling of invoices with no metadata

src/assets/server/rest/v1/schemas/billing/billing-payment-methods-get.json
removed Limit from the schema  - not required anymore
=> payment methods - limit is not mandatory

src/assets/server/rest/v1/docs/e-mobility-oas.json, src/assets/server/rest/v1/schemas/billing/billing-payment-methods-get.json
=> billing - payment methods - no limit

src/assets/schemas/user/user.json
minor change to make it possible to clear the phone numbers
=> users - phone numbers - accept null or empty string as well

src/server/rest/v1/service/AuthService.ts
DRAFT - does it still work when doing B2B calls?
=> fix api user login

src/server/rest/v1/service/AuthService.ts
=> Detect login from react native app

src/authorization/AuthorizationsDefinition.ts
change for [ui!]
- expose full site area address
=> authorization definitions - expose full address

src/assets/server/rest/v1/docs/e-mobility-oas.json, src/assets/server/rest/v1/schemas/company/company-create.json, src/assets/server/rest/v1/schemas/company/company-update.json, src/assets/server/rest/v1/schemas/site/site-create.json, src/assets/server/rest/v1/schemas/site/site-update.json, src/authorization/AuthorizationsDefinition.ts, src/server/rest/v1/service/CompanyService.ts, src/server/rest/v1/service/SiteService.ts, src/storage/mongodb/BillingStorage.ts, src/storage/mongodb/CompanyStorage.ts, src/storage/mongodb/SiteStorage.ts, src/types/Company.ts, src/types/Site.ts, test/api/BillingTest.ts, test/factories/BillingFactory.ts
- Attribute renaming
- Removed not used code
- Typed factories
=> Billing > refactor

src/assets/server/rest/v1/docs/e-mobility-oas.json, src/integration/billing/BillingIntegration.ts, src/storage/mongodb/BillingStorage.ts, src/types/Billing.ts, test/api/BillingPlatformTest.ts, test/factories/BillingFactory.ts
=> Billing platform - finalize transfers

src/integration/billing/BillingIntegration.ts, src/notification/NotificationTask.ts, src/notification/email/EMailNotificationTask.ts, src/notification/remote-push-notification/RemotePushNotificationTask.ts, src/types/UserNotifications.ts
New invoice notifications are never sent!
=> fix - billingInvoice.user is not set

src/authorization/AuthorizationsDefinition.ts, src/server/rest/v1/service/AuthorizationService.ts
- Basic user can now see external company info
=> Show external organisation information

src/server/rest/v1/service/ChargingStationService.ts
- Use correct CS ID instead of CP
=> Fix create/edit charging profile

src/server/rest/v1/service/AuthService.ts
Removed from verify email the creation of the customer counterpart in STRIPE
=> user - postpone sync with stripe

src/assets/server/rest/v1/docs/e-mobility-oas.json, src/authorization/AuthorizationsDefinition.ts, src/integration/billing/BillingIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/server/rest/v1/service/BillingService.ts, src/storage/mongodb/BillingStorage.ts, src/types/Billing.ts, test/api/BillingPlatformTest.ts, test/factories/BillingFactory.ts
=> bp - compute session fees

src/authorization/AuthorizationsDefinition.ts, src/storage/mongodb/BillingStorage.ts, src/types/Billing.ts
While displaying billing connected accounts, we need to display user name instead of business owner ID. 
Front end changes: https://github.com/sap-labs-france/ev-dashboard/pull/3218
=> Add user name to connected accounts feature

src/integration/billing/BillingIntegration.ts, src/integration/billing/stripe/StripeBillingIntegration.ts, src/server/rest/v1/router/util/UtilRouter.ts, src/server/rest/v1/service/BillingService.ts, src/types/Server.ts, src/utils/Utils.ts, test/api/BillingTestHelper.ts, test/api/client/BillingApi.ts
The flow has been modified to avoid the activationLink expiration
=> bp - onboarding flow rework

src/authorization/AuthorizationsDefinition.ts
-  Action.MAINTAIN_PRICING_DEFINITIONS
=> Add charging station missing auth action

src/authorization/AuthorizationsDefinition.ts
- Can stop transactions on sites where he is SA
- Stop only his transactions on other sites
=> Restrict site admin remote stop transaction

package-lock.json, package.json, src/server/rest/v1/service/AuthorizationService.ts, src/server/rest/v1/service/CommonService.ts, src/server/rest/v1/service/SessionHashService.ts
Hotfixes
- Reverting changes on the template for CS DELTA 10692
- Redirect V2 - Moved Temporarily
- Unlock connector - almost always enabled
=> Hotfix - version 2.6.10

package.json, src/integration/billing/stripe/StripeBillingIntegration.ts, src/server/rest/v1/service/BillingService.ts, src/storage/mongodb/BillingStorage.ts, src/types/Billing.ts, test/api/BillingPlatformTest.ts, test/api/BillingTestHelper.ts, test/api/StripeTestHelper.ts
consuming the platformFeeTaxID
=> Billing Platform - Apply tax rate when billing platform fee

src/assets/storage/schemas/configuration/configuration-save.json, src/storage/mongodb/MongoDBStorage.ts
- Should fix read error when replication in secondary not done
- Add readPreference config handling
=> Use collection reference after collection creation

src/storage/mongodb/MongoDBStorage.ts
- Should no longer trigger collection not found
=> Alter read preference in function

src/scheduler/tasks/CloseTransactionsInProgressTask.ts, src/storage/mongodb/TransactionStorage.ts
Avoid a transaction soft stop while the CS sent an ocppBootNotification
=> hotfix - Do not soft stop transaction with no connectors

src/storage/mongodb/PricingStorage.ts
Backend fix for [ev-dashboard](https://github.com/sap-labs-france/ev-dashboard/pull/3356)
=> Adding missing change for site

src/server/ocpp/utils/OCPPUtils.ts
=> bug fix - Charging station template

src/client/ocpi/CpoOCPIClient.ts
=> CPO - Pull Tokens = Do not get tags when there is nothing to do!

src/scheduler/tasks/CloseTransactionsInProgressTask.ts, src/server/ocpp/services/OCPPService.ts, src/server/rest/v1/service/TransactionService.ts
Issue:
When an error occurs with a Soft Stop and no exception has been thrown, there is no indication of what went wrong in the logs !
=> Handle Soft Stop with exception, not boolean

src/server/rest/v1/service/AuthorizationService.ts, src/server/rest/v1/service/ChargingStationService.ts, src/server/rest/v1/service/TransactionService.ts
+ deleted unused check for sites assigned / sites admin and owner (replaced in user abac)
=> aligned failsWithException

src/authorization/AuthorizationsDefinition.ts
Site Admin must see the OCPI TariffID
Added TariffID in Projected fields in Site/Site Area lists for Admin, Site Admin -> Hide the tab OCPI in Site/Site Area
=> Basic and Demo should not see the TariffID

src/async-task/TenantAsyncTask.ts, src/scheduler/TenantSchedulerTask.ts, src/types/Tenant.ts
- Tenant can specify on which env task should be executed
=> Add condiotnal task execution

src/server/CommonUtilsService.ts, src/server/rest/v1/service/AuthorizationService.ts, src/types/Authorization.ts
- Use correct auth check method
- Fix runtime exception
- Add missing CS auth flag
=> Use correct start transaction auth check

src/notification/email/EMailNotificationTask.ts
Strange performance numbers
to be clarified
=> emails - perf - getTenantLogo() was called too often

src/authorization/Authorizations.ts, src/authorization/AuthorizationsDefinition.ts
- duplicated transaction refund to admin when he is also owner
=> admin cannot have admin nor owner roles

src/authorization/AuthorizationsDefinition.ts, src/authorization/DynamicAuthorizationFactory.ts, src/authorization/dynamic-data-source/SitesOwnerUsersDynamicAuthorizationDataSource.ts, src/authorization/dynamic-filters/SitesOwnerUsersDynamicAuthorizationFilter.ts, src/storage/mongodb/TransactionStorage.ts, src/types/Authorization.ts
@Ramzay I have a doubt on SitesOwnerUsersDynamicAuthorizationDataSourceData props ?
=> added sitesOwnerUsers filter

src/client/ocpp/json/JsonRestChargingStationClient.ts, src/server/ocpp/json/JsonOCPPServer.ts, src/server/ocpp/json/web-socket/WSConnection.ts, src/server/ocpp/utils/OCPPUtils.ts
- Prevent last seen update when the WS call is made from the REST server
- Reject onMessage calls when the WsWrapper was rejected during the onOpen phase
=> Ocppj - hot fix

src/server/rest/v1/service/AuthorizationService.ts, src/types/DataResult.ts
@ClaudeROSSI @Ramzay there are also modifications in the backend :)
=> added canGenerateLocalToken and canPing to ocpi auth

src/assets/email/mjml-components/email_eichrecht_table.mjml
=> Version 2.7.5 - fixed eichrecht certificate

src/async-task/AsyncTaskManager.ts, src/async-task/tasks/BillTransactionAsyncTask.ts
- exception handling on floating promises
- minor code cleanup
=> Async task - polish

.vscode/launch.json, ecosystem.config.js, package.json, src/scheduler/tasks/CheckChargingStationTemplateTask.ts, src/server/ocpp/utils/OCPPUtils.ts, src/storage/mongodb/ChargingStationStorage.ts, src/utils/Constants.ts, src/utils/LoggingHelper.ts
Performance and Memory Footprint optimization
- Get Charging Station Pagination
- Skip chargers with manual configuration
- Shrink logged data
=> Charging Station Templates - Apply Template - optimizations
