src/client/ocpp/ChargingStationClientFactory.ts
src/server/ocpp/json/JsonCentralSystemServer.ts
src/server/ocpp/json/JsonRestWSConnection.ts
src/server/ocpp/json/services/JsonChargingStationService.ts
src/server/ocpp/soap/SoapCentralSystemServer.ts
src/server/ocpp/soap/services/SoapCentralSystemService12.ts
src/server/ocpp/soap/services/SoapCentralSystemService15.ts
src/server/ocpp/soap/services/SoapCentralSystemService16.ts
src/start.ts
src/storage/mongodb/MongoDBStorageNotification.ts
src/types/GlobalType.ts

server is disabled.
The buffer was never emptied and it probably has cause huge memory
comsuption triggering crash in the past.

Socket.io: do not fill the notifications array buffer when socket.io

---

package-lock.json
src/server/rest/CentralRestServer.ts

socket.io: force server side connection close with no callback on

---

test/api/ComponentActivationTenantTest.ts

Reconnect test user each time settings are updated to refresh Tenant Hash

Fix user tenant's hash tests

---

src/migration/tasks/UpdateChargingStationStaticLimitationTask.ts
src/scheduler/tasks/CheckChargingStationTemplateTask.ts
src/server/ocpp/utils/OCPPUtils.ts
src/server/rest/CentralRestServer.ts
src/start.ts
src/types/requests/HttpDatabaseRequest.ts
src/utils/Utils.ts

+ Only set sections hash if there's a match;
+ Logic fix for template application at the connector level;
+ Enhance logging for the no template matching CS case.

Templates: keep track of unmatched template sections. 

---

src/client/ocpp/json/JsonRestChargingStationClient.ts

Fix TypeError: Cannot read property 'isConnectionOpen' of null

---

package-lock.json
package.json
src/client/ocpp/ChargingStationClientFactory.ts
src/client/ocpp/json/JsonChargingStationClient.ts
src/client/ocpp/json/JsonRestChargingStationClient.ts
src/client/websocket/WSClient.ts
src/migration/MigrationHandler.ts
src/server/ocpp/json/JsonCentralSystemServer.ts
src/server/ocpp/json/JsonRestWSConnection.ts
src/server/ocpp/json/JsonWSConnection.ts
src/server/ocpp/json/WSConnection.ts
src/server/ocpp/json/WSServer.ts
src/server/rest/v1/service/BillingService.ts
src/types/WebSocket.ts
src/types/ocpp/OCPPClient.ts
src/types/ocpp/OCPPCommon.ts
src/types/ocpp/OCPPHeader.ts
src/types/ocpp/OCPPServer.ts
src/utils/Constants.ts
src/utils/Utils.ts
test/api/client/utils/BaseApi.ts
test/api/ocpp/json/OCPPJsonService16.ts

Update: 
+ Reverted unwanted changes; 
+ Make DB logging unconditional (no tunable for simplicity) where possible (not in WSClient class);  
+ Make console logging conditional to the env type, like all other console logs. 
Update 2: 
+ Remove useless console logging (in WSClient it has to stay).	

Improve WebSocket events logging to help debugging.

---

src/utils/Constants.ts

And name firstName. 
The first might also match valid name fields that should be displayed. Let's see if it really makes the logs less usable.  
SAP Security requirement.

Add GPS coordinates to sensitive data to obfuscate in logs.

---

src/assets/server/ocpp/schemas/boot-notification-request.json

And thus violate the OCPP specs.
Required by SAP Italy.

Charging station vendors string might be longer than 20 characters

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/unit-tests.yml
package-lock.json
package.json

+ Enforce node.js current LTS version
+ Update GitHub CI actions to latest
And that should be enough for the SAP OpenSource review. 

Latest dependencies update.

---

src/assets/server/rest/v1/docs/e-mobility-oas.json
src/server/rest/v1/service/ChargingStationService.ts
src/server/rest/v1/service/security/ChargingStationSecurity.ts
src/types/Server.ts
src/types/requests/HttpChargingStationRequest.ts

Two modifications :
1) Wrapped bucketStream `end` event in a Promise in order to avoid Express to send a 404 status (as the endpoint is full of callback, it seems that the default Express behavior is to send a 404 status)
2) Refactored endpoint route, because `/api/chargingstations/firmware/{filename}` could break with names containing a `/`.

Fix firmware download

---

src/integration/billing/BillingFactory.ts
src/integration/billing/stripe/StripeBillingIntegration.ts

BillingFactory has been changed to avoid creating an instance of StripeBillingIntegration when the settings are not consistent.
The purpose of that change is to prevent that the STRIPE implementation gets called while the connection to the STRIPE account is not yet properly set.

Billing #2183 - check STRIPE settings

---

src/notification/email/EMailNotificationTask.ts

The mailbox is unvailable or the SMTP server will retry by itself.

Do not try to resend mail notification with error 450.

---

package-lock.json
src/assets/server/ocpp/schemas/status-notification-request.json

Fix vendorId length in OCPP-J status notification schema validation.

---

src/notification/email/EMailNotificationTask.ts

(RFC https://tools.ietf.org/html/rfc5321)

SMTP: no retry for error codes that should not 

---

src/integration/billing/BillingIntegration.ts
src/integration/billing/stripe/StripeBillingIntegration.ts
src/server/rest/v1/service/AuthService.ts
src/server/rest/v1/service/BillingService.ts
src/server/rest/v1/service/UserService.ts
src/storage/mongodb/BillingStorage.ts
test/api/BillingStripeIntegrationTest.ts
test/api/BillingStripeTestData.ts
test/api/BillingTest.ts

Checking LIVE MODE flag to switch off some features while we are still in beta mode.
- The purpose is to make it easier to test the payment flow on SLF without any impct on regular users 
- The user synchronization logic as been simplified to avoid some ping-pong between eMobility ad STRIPE.
- Still need to review  the invoice synchronization logic - current implementation is slow and most of the time not necessary anymore
- Includes as well some additional checks to make sure customerID is properly set and  consistent
- Deletion of users on the STRIPE side is not supported anymore! - will be done later

Stripe -  Synch User/Invoices Reorg

---

src/integration/billing/BillingIntegration.ts
src/integration/billing/stripe/StripeBillingIntegration.ts
test/api/BillingStripeIntegrationTest.ts
test/api/BillingStripeTestData.ts

forceSynchronizeUser was not repairing inconsitencies anymore when customerID was set with a wrong value.
This is fixed

billing - repairUser  - to recover from inconsistencies

---

src/integration/billing/stripe/StripeBillingIntegration.ts
src/integration/billing/stripe/StripeHelpers.ts
src/storage/mongodb/BillingStorage.ts
src/types/Billing.ts

**Better abstraction on Billing Errors**
a _BillingError_ interface has been added. it consists of:
- an error message
- a error type (enum)
- an error code (enum) 
- the root cause of the error (i.e.: The error sent by  payment platform itself)
**_StripeHelpers_ Class**
- helpers have been added to provide convenience methods for "consuming" Stripe Errors
**Billing Storage**
- _saveLastBillingError_ method can now persist the last operation error
- This is used to keep track the root cause of the problem when the invoice payment fails
-

Stripe - Billing Error Handling

---

src/assets/config-template-http.json
src/assets/config-template-https.json
src/integration/charging-station-vendor/ChargingStationVendorIntegration.ts
src/scheduler/tasks/CheckChargingStationTemplateTask.ts
src/scheduler/tasks/CheckOfflineChargingStationsTask.ts
src/scheduler/tasks/CheckPreparingSessionNotStartedTask.ts
src/scheduler/tasks/CheckSessionNotStartedAfterAuthorizeTask.ts
src/server/ocpp/json/JsonWSConnection.ts
src/server/ocpp/json/services/JsonChargingStationService.ts
src/server/ocpp/services/OCPPService.ts
src/server/ocpp/utils/OCPPUtils.ts
src/server/rest/v1/service/ChargingStationService.ts
src/server/rest/v1/service/SiteAreaService.ts
src/storage/mongodb/ChargingStationStorage.ts
src/types/ChargingStation.ts
src/utils/Constants.ts
test/api/context/ChargingStationContext.ts
test/api/ocpp/json/OCPPJsonService16.ts

+ Unify OCPP param handling return type;
+ Push down default settings handling in template: fix dynamic connector
adding (e.g. slave)
+ Fix no template at boot notification handling (manual configuration)
+ Improve log message
+ Fix forced template OCPP params application
+ ... too much to list ...

Refactor, cleanup and fix template application code:

---

.eslintrc.json

eslint conf change to avoid np-shadow false positive errors

eslint - typescript-eslint/no-shadow

---

src/integration/billing/BillingFactory.ts
src/integration/billing/BillingIntegration.ts
src/integration/billing/stripe/StripeBillingIntegration.ts
test/api/BillingStripeTestData.ts
test/api/BillingTest.ts

**Stripe Billing Integration**
A ProductionMode property has been added.
- The property is set as soon as possible
- Start/Stop Transaction adapts their checks to the current mode (test or prod)

billing - STRIPE - productionMode

---

src/integration/billing/BillingIntegration.ts
src/integration/billing/stripe/StripeBillingIntegration.ts
src/server/ocpp/utils/OCPPUtils.ts
src/server/rest/v1/service/BillingService.ts
src/server/rest/v1/service/TransactionService.ts
src/server/rest/v1/service/security/SettingSecurity.ts
src/storage/mongodb/SettingStorage.ts
src/storage/mongodb/TransactionStorage.ts
src/types/Billing.ts
src/types/Setting.ts
test/api/BillingStripeTestData.ts
test/api/BillingTest.ts
test/api/context/BillingContext.ts
test/api/context/ContextDefinition.ts
test/config-template.json
test/config.js

The billing settings have been changed to allow entering the stripe connection settings without activating the billing feature.
**isTransactionBillingActivated**
- This new property can be used to switch ON/OFF the billing of transactions.
- This property should only be set to true when the settings are consistent (this will be done later)
This information is used on start transaction and stored in the transaction billing data as the **withBillingActive** flag.
This flag is propagated until the stop transaction.
**Transaction Billing Data Example:**

Billing - settings - explicit activation

---

src/async-task/tasks/TagsImportAsyncTask.ts
src/authorization/Authorizations.ts
src/integration/billing/BillingIntegration.ts
src/integration/billing/stripe/StripeBillingIntegration.ts
src/integration/charging-station-vendor/ChargingStationVendorIntegration.ts
src/migration/tasks/AddUserInTransactionsTask.ts
src/migration/tasks/CleanupMeterValuesTask.ts
src/migration/tasks/RecomputeAllTransactionsConsumptionsTask.ts
src/migration/tasks/RecomputeAllTransactionsWithSimplePricingTask.ts
src/migration/tasks/UpdateConsumptionsToObjectIDsTask.ts
src/notification/NotificationHandler.ts
src/scheduler/tasks/ocpi/OCPIPushCdrsTask.ts
src/server/ExpressUtils.ts
src/server/ocpp/utils/OCPPUtils.ts
src/storage/mongodb/TransactionStorage.ts
src/storage/mongodb/UserStorage.ts
src/utils/Utils.ts
test/api/context/TenantContext.ts

+ Allow to use isEmptyArray on more object. And start doing it a bit.

OCPPUtils.ts: Avoid to loop over empty OCPPMeterValue array.

---

src/server/ocpp/utils/OCPPUtils.ts

Minor change to avoid generating errors when Billing Features are OFF.
- Actually the problem only occured on Transactions that were started before enabling the billing module. So, this was not supposed to happen.

Billing - fix transaction billing errors

---

README.md
src/client/ocpp/json/JsonChargingStationClient.ts
src/client/ocpp/soap/SoapChargingStationClient.ts
src/server/ocpp/json/JsonCentralSystemServer.ts
src/server/ocpp/json/JsonWSConnection.ts
src/server/ocpp/json/WSConnection.ts
src/server/ocpp/json/WSServer.ts
src/server/ocpp/soap/SoapCentralSystemServer.ts
src/server/uWsUtils.ts
test/api/ocpp/json/OCPPJsonService16.ts

Allow charging stations to open two connections with the OCPP-J backend
that will not be identified as the same in the server connection cache Map.
That will close race condition at remove that might occurs in that
case:
Connection one                  | Connection two
CLOSING                         | OPEN
--> CLOSED                     |
--> removed from cache
Should close the issue at remote commands failure for ChargeX. 

Add a UUID to the WSConnection ID:

---

src/integration/billing/stripe/StripeBillingIntegration.ts
src/integration/billing/stripe/StripeHelpers.ts

The customer address is now shown on the invoice header.
Limitation:
- Because of some STRIPE constraints the country is mandatory. 
- When the country is not set the address is not shown at all

Billing - invoice - add customer address

---

src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts
src/server/ocpp/json/services/JsonChargingStationService.ts
src/server/ocpp/utils/OCPPUtils.ts
src/server/rest/v1/service/ChargingStationService.ts
src/server/rest/v1/service/SiteAreaService.ts
src/types/Server.ts
src/types/ocpi/OCPILocation.ts

Update: 
+ reverted to previous behaviour on the phase assignment. 

Dedupe MeterValues in enum + cleanups

---

src/server/rest/v1/service/TransactionService.ts

Add `userID` field back into projectFields. It is needed for the check in `Authorizations.canReadTransaction`. 
It is removed later in the code in case the user who made the request does not have the appropriate permissions (READ on USER entity).

Fix transaction tests

---

src/server/ocpp/json/JsonCentralSystemServer.ts

Ensure the last opened connection for a charging station is found
first.

OCPP-J: iterate the websocket connections Map in reverse order

---

src/migration/MigrationHandler.ts
src/migration/tasks/AddVisualIDPropertyToTagsTask.ts
src/types/Tag.ts

Migration task had to run separately before creating the unique index in the DB.

[1/3] Migration task to add and fill visualID property to tags

---

src/server/rest/v1/service/AuthorizationService.ts

Fixes: `admin that are also site admin or owner can't see everything in the organisation tree`
The problem is that extra filters added in case the user is siteOwner or siteAdmin overlap with the fact that an admin can do anything. For now I can add a check that prevents dynamic filters from being applied in case the user is an admin. But the issue will need to be revisited when Serge is back to see what is the elegant way to address it. (I think that after all the entities will be updated to the new auth concept, it won't be an issue anymore, but I need to check with Serge.)

Bug fix authorization

---

src/integration/billing/stripe/StripeBillingIntegration.ts
src/integration/billing/stripe/StripeHelpers.ts

Stripe expects a Two-letter country code (ISO 3166-1 alpha-2)
- The country entered in the address of the customer is converted to the Alpha 2 code when creating/updating the corresponding data on the stripe side.
- Same logic applies when creating a payment method. The billing details information attached to the card information benefit from the same country code conversion logic.
**Known restriction**: The end user must provide the country name using his/her locale. In other words, entering Germany, when  your language is 'de', is not supported. A German end-user has to enter 'Deutschland' instead!

Billing - stripe - country code in addresses

---

src/types/Server.ts
src/utils/Logging.ts
src/utils/Utils.ts

And use try catch construct to avoid crashing the execution if the
cloning fails.

Logging: use lodash clone to avoid circular structure conversion error

---

src/integration/billing/stripe/StripeHelpers.ts

Billing Details - Make it secure when the country is not set or empty

Billing stripe country code in address

---

src/integration/billing/stripe/StripeBillingIntegration.ts
src/server/rest/v1/service/TransactionService.ts
src/storage/mongodb/TransactionStorage.ts
src/types/Billing.ts

The invoice ID was available but not the invoice Number. This has been fixed.
Also changing the way we detect billing inconsistencies. now relying on BillingStatus.FAILED state.

billing - show Invoice Number

---

src/integration/billing/BillingIntegration.ts
src/storage/mongodb/BillingStorage.ts
src/storage/mongodb/UserStorage.ts
src/types/Server.ts
test/api/BillingStripeTestData.ts
test/api/BillingTestDataCleanupTest.ts

The purpose of these changes is to make it possible for the customer to experiment the stripe integration with a stripe test account.
As a consequence, we need to be able to clear all test data once the customer goes live.
new methods have been added to:
-  delete all invoices with **liveMode** set to false and clear the corresponding billingData aattched to the corresponding transactions.
- clear all users having a billingData with liveMode set to false. The purpose here is to get rid of all STRIPE customer references.
So far, no endpoints are using the new methods.
However, utBilling tests can be used to check the behavior!

Billing - test data cleanup

---

src/integration/billing/stripe/StripeBillingIntegration.ts
src/storage/mongodb/UserStorage.ts
src/utils/FeatureToggles.ts
test/api/BillingTest.ts

**Lazy Synch Users**
- a LAZY synchronize user mode as been introduced to AVOID the need to create all customers (on the STRIPE).
- The user synchronization is now postponed and done only when the end-user creates its first payment method.
The advantage of this approach is that the billing setup (and the activation of the billing of the transaction) does not require to wait for a complete synchronization.
The "User in Errors" tab has been adapted as well. Users with no Billing Data are not shown as "**Users in Error**" anymore

Billing - lazy synch user

---

src/integration/billing/BillingIntegration.ts
src/storage/mongodb/BillingStorage.ts
src/storage/mongodb/MongoDBStorage.ts
test/api/BillingTest.ts

Periodic Billing:
- index has been added to make sure we get a stable bevaviour when the number of invoices increases.
> {  fields: { createdOn: 1 } }
- pagination has been added to make sure we do not load all invoices in memory
- same filtering logic applies when testing but on the current day (instead of the previous month)
- unused convenience methods have been removed from BillingStorage
- tests have been adapted a bit

Billing optimize periodic billing

---

src/integration/billing/stripe/StripeBillingIntegration.ts

This is a proposal for a temporary solution to allow activating the billing on SLF while enabling it only for external users.
The temporary solution simply checks for the id of the SLF tenant and considers the user to be internal when his/her email ends with '@sap.com'

billing - do not bill internal users on SLF

---

src/integration/billing/BillingIntegration.ts
src/integration/billing/stripe/StripeBillingIntegration.ts
src/integration/billing/stripe/StripeHelpers.ts

Some optimization on the **chargeInvoice**() method to avoid fetching several times the stripe invoice data.
Note: method **synchronizeAsBillingInvoice** has been removed from the **BillingIntegration** layer because only the concrete Stripe implementation calls it.

Billing - optimize charge invoice

---

src/integration/billing/BillingIntegration.ts
src/integration/billing/stripe/StripeBillingIntegration.ts
src/types/Billing.ts

Invoice status from STRIPE includes stuff like VOID, UNCOLLECTIBLE and DELETED.
- The code has been changed to make sure these additional states do not have any side-effect when transitioning the invoices from one state to the other.
Note:
- Both the web app and mobile apps need to be changed to properly display these additional invoice statuses. This will be done separately (the corresponding issue has been created already).

Billing - invoice statuses

---

src/integration/smart-charging/SmartChargingIntegration.ts

The reason for sorting the profiles is, that we need to ensure to first limit the stations with the lower limits, before we set the other ones free with higher limits. (Otherwise there are transition periods with two high limits, which could exceed the overall limit)

Smart Charging > Sort charging profiles before applying

---

src/integration/billing/stripe/StripeBillingIntegration.ts

just making sure the currency format on our side matches the one defined in the pricing settings.
i.e. : uppercase on our side (while lowercase in stripe invoices)

billing - invoice - normalize currency

---

src/async-task/AsyncTaskManager.ts

Very tricky issue due to Promise.map!
When **n** async tasks were in a PENDING state. The async task manager was running **n** times the lastest one!
This leading to an exception when the task tries to acquire an exclusive lock.

HOTFIX - async task manager - running same task several times!!!

---

src/integration/billing/stripe/StripeBillingIntegration.ts

hotfix - start transaction not possible for sap employees anymore because start transcation checks is gettiongs null insetead of an empty array of error codes.

start transaction - error code must not be null

---

src/assets/server/rest/v1/schemas/tenant/tenant-create.json

tenant created by the unit tests had a different id than the expected one.
This was due to the validator of the create tenant endpoint.

tenant creation endpoint - schema validation accepting the ID

---

package-lock.json
package.json
test/api/client/utils/CrudApi.ts

Removed dependency to safe-url-assembler
- The URL generation used to test REST endpoints has been adapted
- URL path is properly encoded using **encodeURIComponent** method.

Rest endpoints - encode url params

---

src/assets/server/rest/v1/schemas/transaction/transactions-get.json
src/storage/mongodb/TransactionStorage.ts
src/types/requests/HttpTransactionRequest.ts

Backend changes required to display summary statistics. If the status of request is "Statistics": "ongoing", create a summary similar to "Statistics": "history" but with different parameters from the DB.

Display footer stats for current charging sessions

---

src/integration/billing/stripe/StripeBillingIntegration.ts
src/utils/I18nManager.ts

Start time shown on each invoice item was not taking into account the transaction timezone.
This has been fixed!

Billing - take into account transaction timezone

---

src/integration/billing/BillingIntegration.ts
src/integration/billing/stripe/StripeBillingIntegration.ts
test/api/BillingStripeTestData.ts
test/api/BillingTest.ts

For a DRAFT invoice, the final invoice date is only known when it gets finalized. The invoice synchronization takes now the finalized_at property into consideration.
The side effect of that change is that the initial date gets updated during the periodic billing process. This as an impact on the pagination logic in place when going thru the list of invoices of the previous month. The pagination logic has been updated to make sure the periodic billing process does not 'forget' any invoices !

Billing - periodic operation -  some fixes

---

src/async-task/tasks/BillTransactionAsyncTask.ts
src/integration/billing/stripe/StripeBillingIntegration.ts
src/locking/LockingHelper.ts
test/config.js

Potential conflicts have been detected when two async billing tasks for the same user are running in parallel and generating stripe invoice items.
The side effect, is that the first invoice was containing 2 invoice items while the second one was failing because no pending invoice items were available (i.e.: nothing to bill).
The solution here relies on the acquireExclusiveLock() on the user, with a time out to make sure the 2nd invoice waits for the first one to complete.

billing - asyncTask changed to prevent invoicing conflicts

---

src/assets/server/rest/v1/schemas/tag/tags-get.json
src/assets/server/rest/v1/schemas/user/users-get.json

limit was excluded from the request so set to 100 by default but the constant for EXPORT_PAGE_SIZE was always (as it has to be) to 1000
So at the second loop in exportToCsv method, at the end, skip was set to 2000 even if we retrieved only 200 from db

added limit to schema validator

---

src/client/ocpi/CpoOCPIClient.ts
src/server/ocpi/OCPIUtils.ts
src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/OCPIUtilsService.ts

Fix computation of evse_uid and evse_uid when a charging station contains several charge points with the flag cannotChargeInParallel set to true

Fix computation of evse_uid and evse_uid when a charging station contains several charge points with the flag cannotChargeInParallel set to true

---

src/integration/smart-charging/sap-smart-charging/SapSmartChargingIntegration.ts

Charging station under charging profile was set to undefined, as a result of which exceptions were being thrown when siteID, siteAreaID or companyID from chargingStation was being accessed.

Adding changes to handle missing charging station in charging profile.

---

src/integration/pricing/ConsumptionPricer.ts
src/integration/pricing/PricingEngine.ts
src/types/Pricing.ts
test/api/BillingTest.ts
test/api/BillingTestHelper.ts

Some changes to make sure the location of the charging station is taken into account when checking "time range" restrictions while pricing the charging session consumption.

pricing - consider transaction timezone 

---

src/integration/pricing/ConsumptionPricer.ts
src/integration/pricing/PricingEngine.ts

consumption pricer now properly handles transactions where the timezone is not set

pricing - warning when timezone is unknown

---

test/api/OCPPCommonTests.ts
test/api/StatisticsTest.ts
test/api/TransactionCommonTests.ts
test/api/TransactionTest.ts
test/api/client/CentralServerService.ts
test/api/context/ContextBuilder.ts
test/api/context/ContextDefinition.ts

When the pricing module is ON
- A default tariff is created (price: 1 EUR/kWh) on all test tenants
This to make sure the test behaves as before when using the Simple Pricing logic.
Todo: cleanup some test helpers that are not used anymore !

pricing - fix - mochatest create context

---

src/storage/mongodb/CarStorage.ts
src/storage/mongodb/CompanyStorage.ts
src/storage/mongodb/SiteAreaStorage.ts
src/storage/mongodb/SiteStorage.ts
src/storage/mongodb/TenantStorage.ts

The Tenant's logo URL concatenation with "LastChangedOn" property fails if the tenant does not have the property. In addition, the parameter is not used in the `handleGetTenantLogo` method, so can be removed

Fixed tenant logo without Tenant's "LastChangedOn" property

---

src/migration/MigrationHandler.ts
src/migration/tasks/RepairTransactionPricedAtZeroTask.ts

Migration task to fix sessions that have been priced at zero because they were started with the "simple pricing logic" and terminated with the "built-in pricing engine".
This mainly impact the sessions of the slfcah (charge at home). But some other tenants may have the same issue.
The migration task simply price again the transaction and the corresponding consumption data.

pricing - repair sessions started the 7th dec and terminated the day after

---

src/integration/pricing/ConsumptionPricer.ts

Pricing with no restrictions do not check the transaction timezone anymore.
To be on on the safe side, a fallback is necessary to make sure the timezone is always set (fallback to the site area or the site). This will be fixed in another PR!

consumption pricer - Check timezone only when necessary

---

src/integration/billing/stripe/StripeBillingIntegration.ts
src/migration/tasks/RepairInvoiceInconsistencies.ts

We still have a random situation where invoices to not have any sessions and the root cause is still not clear to me.
This PR includes :
- The repair tasks again to fix invoices having the problem.
- A workaround to retry the STRIPE invoice sync when the problem occurs

billing - repair again invoices with no sessions

---

src/assets/server/rest/v1/schemas/notification/notifications-end-user-error-report.json
src/server/rest/v1/service/NotificationService.ts

Allow to not pass mobile phone to report error (to debug mobile app)
Also, the mobile number is already fetched server-side when the request is processed

Allow to not pass mobile phone to report error (API call)

---

src/integration/pricing/ConsumptionChunkPricer.ts

I would like to change the logic for the **flat fee** and make sure we do not bill it if no energy has been delivered.
The purpose of that change is to make sure the end-user **do not pay several times** the Flat Fee, when he plugs/unplugs his car several times without charging at all.

pricing - prevent flat fee if no consumption

---

src/authorization/AuthorizationsDefinition.ts
src/server/rest/v1/service/AuthorizationService.ts
src/server/rest/v1/service/UtilsService.ts
src/storage/mongodb/TagStorage.ts

Goal of this PR:
- Move issuer check in auth definition when possible
- Update Auth definition with issuer constraint on actions
I added 2 TODOs:
- checkAndGetUserAuthorization is used in multiple components and sometimes we call the function for USER and READ action with checkIssuer = true or false which should bypass the LocalIssuer filter. Because of this we cannot update the auth definition for USER Action.READ and I don't know if the checkIssuer was put in place due to limitations I don't see !
- checkAndGetChargingStationAuthorization not using yet the new auth, so cannot move the issuer check yet.

Issuer filter cleanup

---

src/integration/billing/BillingFacade.ts
src/integration/billing/BillingIntegration.ts

Free Access:
- Putting back the check of the free access to the **BillingAbstraction.checkStartTransaction()** METHOD
- Moved down the check of the stripe **customerID** 
Note: This also impacts the check of the "siteArea.accessControl" flag! - we potencially had the same problem!

billing - check free access before checking customerID

---

src/integration/billing/stripe/StripeBillingIntegration.ts

stripe URLs to invoices may expire ... fix: we ask for a fresh URL just before downloading

invoice - get fresh url for downloading

---

src/integration/pricing/ConsumptionChunkPricer.ts
test/api/BillingTest.ts
test/api/BillingTestHelper.ts

Pricing the charging time gives inconsistent results when the meter values pace and the step size are different.
The typical situation where the result is unpredictable is the one below:
- Charging station sends data every 56 seconds.
- Pricing definition is set to price the chatting time every minute (60s).
With the current logic, some steps are not priced at all. The final price is simply wrong because some seconds are skipped .
Known workaround: 
- Get rid of the step size in the pricing definition. A step size of 60 seconds is simply useless!
Example of wrong data:

Pricing - inconsistent price when step is set

---

src/storage/mongodb/TransactionStorage.ts

Minor change to make sure the invoiceID is always persisted as an ObjectId().
Migration of old transactions should be necessary, but the information is not yet used by the UI and a SynchronizeInvoice endpoint is planned. This endpoint will somehow fix old transactions as well.

Billing - convert invoiceID to ObjectID

---

src/server/ocpp/utils/OCPPUtils.ts

The problem occurs because of a wrong amperage limit on connector level in the database:
```
connectors: [{id: null, connectorId: 1, currentInstantWatts: 0, currentStateOfCharge: 0,…},…]
0: {id: null, connectorId: 1, currentInstantWatts: 0, currentStateOfCharge: 0,…}
amperage: 96
amperageLimit: 18
chargePointID: 1
connectorId: 1
currentInactivityStatus: "I"
currentInstantWatts: 0
currentStateOfCharge: 0
currentTagID: null
currentTotalConsumptionWh: 0
currentTotalInactivitySecs: 0
currentTransactionDate: null
currentTransactionID: 0
currentType: null
currentUserID: null
errorCode: "NoError"
id: null
info: null
numberOfConnectedPhase: null
phaseAssignmentToGrid: {csPhaseL1: "L1", csPhaseL2: "L2", csPhaseL3: "L3"}
power: 22080
status: "Available"
statusLastChangedOn: …
```

Fix - wrong amperage limit

---

src/validator/SchemaValidator.ts
test/api/AuthenticationTest.ts
test/api/CarTest.ts
test/api/OCPPCommonTests.ts
test/api/SiteAreaOrgTest.ts
test/api/TenantTest.ts
test/api/TransactionCommonTests.ts

Throw Http Bad Request (400) for HTTP param validations instead of Internal Server Error (500)
Aligned Unit Tests

Throw Http Bad Request (400) for HTTP param validations instead of Internal Server Error (500)

---

src/authorization/AuthorizationsDefinition.ts
src/server/rest/v1/service/TransactionService.ts
src/storage/mongodb/TransactionStorage.ts

This fixes the export / push CDR authorizations:
- Use projected field for export CDR: in order to have the ocpi & ocpiWithCdr flags that are required to authorize the action.
- When no projected fields are set, by default we add the flags as it is required for the push CDR
@ClaudeROSSI I will create an issue to optimize the pushCDR endpoint, so that it will also use projected fields

Add ocpi data flags for export/push cdr

---

src/integration/charging-station-vendor/ChargingStationVendorFactory.ts
src/integration/charging-station-vendor/wallbox/WALLBOXChargingStationVendorIntegration.ts
src/types/ChargingStation.ts

This is a quick fix for Wall Box Chargers not accepting charging profiles on stack levels other than 0. 
On a long term we should refactor the charging profile logic to use stack level 0 whenever possible.

Wall Box Chargers - Custom Vendor Integration

---

src/server/rest/v1/service/UserService.ts

I had this issue when my `capabilities` attribute was empty for my chargingStation (created manually)

Fix "Cannot read properties of null (reading 'supportChargingProfiles')"
